# Generated by agentseam 0.3.5 -- bundle("vscode_copilot"). Do not hand-edit, except the
# HANDLER block below (between "agentseam handler >>>" and "<<< agentseam handler"),
# which is exactly what this file leaves for you to fill in.
#
# Self-contained: stdlib only, no "import agentseam" anywhere in this file. Regenerate
# with `agentseam.bundler.bundle("vscode_copilot")` (same agentseam version -> identical bytes,
# except your own edits inside the handler block) rather than patching this by hand.
# https://github.com/open-coder-ai/agentseam

from __future__ import annotations

import contextlib
import io
import json
_json = json
import os
import sys

import fnmatch as _chock_fnmatch
import re as _chock_re
import os as _chock_os
import shlex as _chock_shlex
import shutil as _chock_shutil
import subprocess as _chock_subprocess
from datetime import datetime as _chock_datetime, timezone as _chock_timezone
from pathlib import Path as _chock_Path
from pathlib import PurePosixPath as _chock_PurePosixPath, PureWindowsPath as _chock_PureWindowsPath
import traceback
import warnings as _warnings

# ------------------------------------------------------------------------------
# contract (agentseam 0.3.5)

"""Canonical event vocabulary, normalized envelope, and decision type."""



SESSION_START = "session_start"
SESSION_END = "session_end"
PROMPT_SUBMIT = "prompt_submit"
PRE_TOOL = "pre_tool"
POST_TOOL = "post_tool"
TOOL_FAILURE = "tool_failure"
PRE_COMPACT = "pre_compact"
STOP = "stop"
SUBAGENT_START = "subagent_start"
SUBAGENT_STOP = "subagent_stop"
INSTRUCTIONS_LOADED = "instructions_loaded"
FILE_CHANGED = "file_changed"

UNKNOWN = "unknown"

EVENTS = (
    SESSION_START,
    SESSION_END,
    PROMPT_SUBMIT,
    PRE_TOOL,
    POST_TOOL,
    TOOL_FAILURE,
    PRE_COMPACT,
    STOP,
    SUBAGENT_START,
    SUBAGENT_STOP,
    INSTRUCTIONS_LOADED,
    FILE_CHANGED,
)


class Event:
    """One agent lifecycle event, normalized."""

    __slots__ = (
        "agent",
        "command",
        "content",
        "cwd",
        "event",
        "output",
        "path",
        "prompt",
        "raw",
        "session_id",
        "tool",
        "tool_use_id",
    )

    def __init__(
        self,
        agent,
        event,
        *,
        tool=None,
        command=None,
        path=None,
        content=None,
        output=None,
        prompt=None,
        session_id=None,
        tool_use_id=None,
        cwd=None,
        raw=None,
    ):
        self.agent = agent
        self.event = event
        self.tool = tool
        self.command = command
        self.path = path
        self.content = content
        self.output = output
        self.prompt = prompt
        self.session_id = session_id
        self.tool_use_id = tool_use_id
        self.cwd = cwd
        self.raw = raw if raw is not None else {}

    def __repr__(self):  # pragma: no cover - debugging aid
        return "Event(%s/%s tool=%r path=%r)" % (self.agent, self.event, self.tool, self.path)


ALLOW = "allow"
DENY = "deny"
ESCALATE = "escalate"
TRANSFORM = "transform"
WARN = "warn"
VOUCH = "vouch"

# Pre-ACS-alignment names. Same strings as their ACS-named counterparts, so every existing
# `is`/`==` comparison against the old constant keeps working untouched.
ASK = ESCALATE
REWRITE = TRANSFORM

_CANONICAL_OUTCOMES = (ALLOW, DENY, ESCALATE, TRANSFORM, WARN, VOUCH)

# The literal spellings a caller might still pass to Decision(outcome, ...) directly, mapped
# to the value that now backs them. Only needed for the raw-string constructor path --
# Decision.ask()/.rewrite() below build the canonical outcome themselves.
_LEGACY_SPELLING = {"ask": ESCALATE, "rewrite": TRANSFORM}


class Decision:
    """What a handler wants to happen. Adapters translate this to vendor dialect."""

    __slots__ = ("context", "evidence", "outcome", "reason", "updated_input")

    #: Classmethods kept only so existing callers keep constructing; see .ask()/.rewrite().
    DEPRECATED_ALIASES = frozenset({"ask", "rewrite"})

    def __init__(self, outcome, reason=None, updated_input=None, evidence=None, context=None):
        outcome = _LEGACY_SPELLING.get(outcome, outcome)
        if outcome not in _CANONICAL_OUTCOMES:
            raise ValueError("unknown outcome: %r" % (outcome,))
        self.outcome = outcome
        self.reason = reason
        self.updated_input = updated_input
        self.evidence = evidence or {}
        self.context = context

    @classmethod
    def allow(cls, reason=None, evidence=None, context=None):
        return cls(ALLOW, reason, evidence=evidence, context=context)

    @classmethod
    def deny(cls, reason, evidence=None, context=None):
        return cls(DENY, reason, evidence=evidence, context=context)

    @classmethod
    def escalate(cls, reason, evidence=None, context=None):
        """Defer the action to the host's own approval path (ACS `escalate`)."""
        return cls(ESCALATE, reason, evidence=evidence, context=context)

    @classmethod
    def ask(cls, reason, evidence=None, context=None):
        """Deprecated alias of escalate() -- kept so existing callers keep constructing."""
        _warnings.warn("Decision.ask() is deprecated; use Decision.escalate()", DeprecationWarning, stacklevel=2)
        return cls.escalate(reason, evidence=evidence, context=context)

    @classmethod
    def transform(cls, updated_input, reason=None, evidence=None, context=None):
        """Replace the tool input wholesale (ACS `transform`, at whole-value granularity)."""
        return cls(TRANSFORM, reason, updated_input=updated_input, evidence=evidence, context=context)

    @classmethod
    def rewrite(cls, updated_input, reason=None, evidence=None, context=None):
        """Deprecated alias of transform() -- kept so existing callers keep constructing."""
        _warnings.warn("Decision.rewrite() is deprecated; use Decision.transform()", DeprecationWarning, stacklevel=2)
        return cls.transform(updated_input, reason, evidence=evidence, context=context)

    @classmethod
    def warn(cls, reason=None, evidence=None, context=None):
        """Permit the action with no change, recording a warning (ACS `warn`)."""
        return cls(WARN, reason, evidence=evidence, context=context)

    @classmethod
    def vouch(cls, reason=None, evidence=None, context=None):
        return cls(VOUCH, reason, evidence=evidence, context=context)

    def __repr__(self):  # pragma: no cover - debugging aid
        return "Decision(%s, %r)" % (self.outcome, self.reason)


def degraded_from(decision):
    """What this decision was before the dispatcher reduced it, or None."""
    return (decision.evidence or {}).get("degraded_from")


def tool_input_of(raw):
    """The tool's arguments as a dict, decoding the JSON-string form some vendors send."""
    if isinstance(raw, dict):
        return raw
    if isinstance(raw, str) and raw.lstrip()[:1] == "{":
        try:
            parsed = _json.loads(raw)
        except (ValueError, RecursionError):
            # JSONDecodeError is a ValueError; a string nested past the interpreter's
            # limit raises RecursionError instead, and neither is an input to crash on.
            return {}
        if isinstance(parsed, dict):
            return parsed
    return {}


# ------------------------------------------------------------------------------
# windows helper (used by the vscode_copilot adapter)

"""PowerShell's one rule that breaks hook commands, shared by the vendors it affects."""


#: `pwsh -Command` exits 1 whenever the last native command failed, whatever its code, so a
#: hook's exit 2 (block) reached the host as 1 (a non-blocking error): openai/codex#48183.
#: When no native command ran at all (the interpreter is not on PATH), $LASTEXITCODE is $null
#: and `exit $null` is 0 -- an allow; nothing judged the call, so that refuses (2) instead.
_KEEP_EXIT = "; if ($null -eq $LASTEXITCODE) { exit 2 }; exit $LASTEXITCODE"

#: The suffix before the $null guard; an entry carrying it is upgraded, not suffixed twice.
_BARE_EXIT = "; exit $LASTEXITCODE"


def powershell_command(command):
    """`command` rewritten so PowerShell will actually run it and keep its exit code."""
    body = command if command.lstrip().startswith("&") else "& " + command
    body = body.rstrip()
    if body.endswith(_KEEP_EXIT):
        return body
    if body.endswith(_BARE_EXIT):
        body = body[: -len(_BARE_EXIT)]
    return body + _KEEP_EXIT


# ------------------------------------------------------------------------------
# vscode_copilot adapter

"""VS Code Copilot (agent mode) and GitHub Copilot CLI adapter."""



AGENT = "vscode_copilot"

EVENT_MAP = {
    "PreToolUse": PRE_TOOL,
    "PostToolUse": POST_TOOL,
    "UserPromptSubmit": PROMPT_SUBMIT,
    "SessionStart": SESSION_START,
    "SubagentStart": SUBAGENT_START,
    "SubagentStop": SUBAGENT_STOP,
    "Stop": STOP,
    "preToolUse": PRE_TOOL,
    "postToolUse": POST_TOOL,
    "userPromptSubmitted": PROMPT_SUBMIT,
    "sessionStart": SESSION_START,
    "sessionEnd": SESSION_END,
    "subagentStop": SUBAGENT_STOP,
    "agentStop": STOP,
}

MEMORY_TOOLS = ("memory", "copilot_memory")
MEMORY_WRITE_COMMANDS = ("create", "str_replace", "insert")

#: Copilot's hooks reference ("Tool names for hook matching", read 2026-09-01): runtime
#: names bash (Unix) / powershell (Windows), reported as Claude's Bash in PascalCase payloads.
SHELL_TOOLS = ("bash", "powershell", "Bash")


_CODEX_MARKERS = ("turn_id", "permission_mode")

_CURSOR_MARKERS = ("model", "cursor_version", "conversation_id", "generation_id", "workspace_roots")

_CLAIMABLE = tuple(name for name in EVENT_MAP if name[:1].islower())

_VSCODE_ENVELOPE = "timestamp"

#: Copilot CLI's own camelCase input (docs.github.com/en/copilot/reference/hooks-configuration,
#: read 2026-09-27): {sessionId, timestamp, cwd, toolName, toolArgs[, toolResult]} and no event
#: name at all. `toolArgs` is documented as the parsed arguments; the JSON-string form earlier
#: CLI builds sent is decoded too.
_CLI_ARGS = "toolArgs"
_CLI_RESULT = "toolResult"
_CLI_KEYS = (_CLI_ARGS, "toolName", "sessionId")

#: The camelCase `agentStop` payload (live capture, Windows, 2026-09-28): {sessionId, timestamp
#: (epoch ms), cwd, transcriptPath, stopReason, stop_hook_active} and no event name either.
_CLI_STOP = "stopReason"


def _name(raw):
    """The payload's own event name as text; None when it names none, UNKNOWN when the
    value is not text (a list or object cannot be looked up, and would raise if tried)."""
    if not isinstance(raw, dict):
        return None
    name = raw.get("hook_event_name") or raw.get("hookEventName")
    if name is None or isinstance(name, str):
        return name
    return UNKNOWN


def claims(raw):
    """True for a payload from either product."""
    if not isinstance(raw, dict):
        return False
    name = _name(raw)
    if name in EVENT_MAP and _VSCODE_ENVELOPE in raw and "turn_id" not in raw:
        return True
    if any(k in raw for k in _CODEX_MARKERS + _CURSOR_MARKERS):
        return False
    if name in _CLAIMABLE:
        return True
    if name is None and (
        _CLI_ARGS in raw or _CLI_STOP in raw or ("toolName" in raw and ("sessionId" in raw or _VSCODE_ENVELOPE in raw))
    ):
        # A CLI call may omit toolArgs; unclaimed, it would pass unseen as "unrecognized".
        return True
    ti = raw.get("tool_input")
    return raw.get("tool_name") in MEMORY_TOOLS and isinstance(ti, dict) and "command" in ti


def _tool_input(raw):
    """The tool's arguments: VS Code's `tool_input`, else the CLI's `toolArgs` (object or JSON text)."""
    ti = raw.get("tool_input")
    return tool_input_of(raw.get(_CLI_ARGS) if ti is None else ti)


def is_cli_native(raw):
    """True for Copilot CLI's camelCase payloads, which get its top-level permission answer."""
    if not isinstance(raw, dict):
        return False
    name = _name(raw)
    if name is None:
        return any(k in raw for k in _CLI_KEYS)
    return name in _CLAIMABLE


def _cli_output(raw):
    result = raw.get(_CLI_RESULT)
    return result.get("textResultForLlm") if isinstance(result, dict) else None


def _implied_name(raw):
    """The event a payload with no name of its own is: agentStop, postToolUse, else preToolUse."""
    if _CLI_STOP in raw and _CLI_ARGS not in raw:
        return "agentStop"
    return "postToolUse" if _CLI_RESULT in raw else "preToolUse"


def parse(raw):
    if not isinstance(raw, dict):
        return Event(AGENT, UNKNOWN, raw=raw)
    ti = _tool_input(raw)
    tool = raw.get("tool_name") or raw.get("toolName")
    path = content = None
    if tool in MEMORY_TOOLS:
        if ti.get("command") in MEMORY_WRITE_COMMANDS:
            path = ti.get("path") or "/memories/"
            content = ti.get("file_text") or ti.get("new_str") or ti.get("insert_text")
        else:
            path = ti.get("path")
    else:
        path = ti.get("filePath") or ti.get("file_path") or ti.get("path")
        content = ti.get("content") or ti.get("newText") or ti.get("new_str") or ti.get("file_text")
    name = _name(raw) or _implied_name(raw)
    return Event(
        AGENT,
        EVENT_MAP.get(name, UNKNOWN),
        tool=tool,
        command=ti.get("command") if tool not in MEMORY_TOOLS else None,
        path=path,
        content=content,
        prompt=raw.get("prompt"),
        output=raw.get("tool_output") or raw.get("tool_response") or _cli_output(raw),
        session_id=raw.get("session_id") or raw.get("sessionId"),
        tool_use_id=raw.get("tool_use_id"),
        cwd=raw.get("cwd"),
        raw=raw,
    )


def is_memory_write(event):
    """True when this event is a memory-tool content write (VS Code's memory surface)."""
    ti = _tool_input(event.raw)
    return event.tool in MEMORY_TOOLS and ti.get("command") in MEMORY_WRITE_COMMANDS


_TOP_LEVEL_BLOCK = (PROMPT_SUBMIT, POST_TOOL)

_NESTED_BLOCK = (STOP, SUBAGENT_STOP)


def _echoed_name(event):
    """This event's own vendor spelling, out of the payload; VS Code's name if there is none."""
    return _name(event.raw) or REVERSE_EVENT_MAP.get(event.event, "PreToolUse")


def _refusal_reason(decision):
    """One reason string for the block dialects, which have no ask and no rewrite."""
    reason = decision.reason or "blocked by policy"
    if decision.outcome == ASK:
        return reason + " (confirmation requested; this event cannot prompt, so it blocks)"
    if decision.outcome == REWRITE:
        return reason + " (input rewrite requested; this event cannot modify input, so it blocks)"
    return reason


DECISION_VOCABULARY = frozenset({"allow", "deny", "ask", "block"})

#: The permission-object dialect's one reason field, named four times below.
_PERMISSION_DECISION_REASON = "permissionDecisionReason"


def _top_level_block_body(decision):
    """The dict to serialize, or None where nothing blocks -- always exit 0."""
    if decision.outcome in (ALLOW, VOUCH):
        return None
    return {"decision": "block", "reason": _refusal_reason(decision)}


def _nested_block_body(decision, event):
    if decision.outcome in (ALLOW, VOUCH):
        return None
    out = {"hookEventName": _echoed_name(event), "decision": "block", "reason": _refusal_reason(decision)}
    return {"hookSpecificOutput": out}


def _pre_tool_out(decision, event):
    out = {"hookEventName": _echoed_name(event)}
    if decision.outcome == VOUCH:
        out["permissionDecision"] = "allow"
        if decision.reason:
            out[_PERMISSION_DECISION_REASON] = decision.reason
    elif decision.outcome == DENY:
        out["permissionDecision"] = "deny"
        out[_PERMISSION_DECISION_REASON] = decision.reason or "blocked"
    elif decision.outcome == ASK:
        out["permissionDecision"] = "ask"
        out[_PERMISSION_DECISION_REASON] = decision.reason or "confirmation required"
    elif decision.outcome == REWRITE:
        out["permissionDecision"] = "allow"
        out["updatedInput"] = decision.updated_input
        if decision.reason:
            out[_PERMISSION_DECISION_REASON] = decision.reason
    return out


def _cli_pre_tool_out(decision):
    """The CLI's documented top-level answer; it has no input rewrite, so a rewrite blocks."""
    if decision.outcome == VOUCH:
        out = {"permissionDecision": "allow"}
        if decision.reason:
            out[_PERMISSION_DECISION_REASON] = decision.reason
        return out
    if decision.outcome == ASK:
        return {"permissionDecision": "ask", _PERMISSION_DECISION_REASON: decision.reason or "confirmation required"}
    return {"permissionDecision": "deny", _PERMISSION_DECISION_REASON: _refusal_reason(decision)}


def respond(decision, event):
    """Three dialects, one per event group -- not one gate shape everywhere."""
    import json as _json  # noqa: PLC0415 (bundler.py keeps this vendored file's own function-local
    # imports untouched -- only top-level imports get hoisted into a bundle; see
    # test_function_local_imports_are_left_alone -- so hoisting this would only move it, not
    # remove it, while touching every response line for no behavioral gain)

    if event.event in _TOP_LEVEL_BLOCK:
        body = _top_level_block_body(decision)
        return ("", 0) if body is None else (_json.dumps(body), 0)

    if event.event in _NESTED_BLOCK:
        body = _nested_block_body(decision, event)
        return ("", 0) if body is None else (_json.dumps(body), 0)

    if event.event != PRE_TOOL or decision.outcome == ALLOW:
        return "", 0

    if is_cli_native(event.raw):
        return _json.dumps(_cli_pre_tool_out(decision)), 0

    return _json.dumps({"hookSpecificOutput": _pre_tool_out(decision, event)}), 0


REVERSE_EVENT_MAP = {
    PRE_TOOL: "PreToolUse",
    POST_TOOL: "PostToolUse",
    PROMPT_SUBMIT: "UserPromptSubmit",
    SESSION_START: "SessionStart",
    SUBAGENT_START: "SubagentStart",
    SUBAGENT_STOP: "SubagentStop",
    STOP: "Stop",
}


def hook_config(canonical_events, command, matcher=None):  # noqa: ARG001 (every adapter's
    # hook_config(..., matcher=) is called uniformly by install.py/install_identity.py;
    # VS Code has no per-tool matcher to honour, but the parameter stays for interface parity)
    """The hooks file VS Code actually parses: an object keyed by event name."""
    hooks = {}
    for ev in canonical_events:
        name = REVERSE_EVENT_MAP.get(ev)
        if name:
            windows = powershell_command(command)
            entry = {"type": "command", "command": command, "bash": command, "powershell": windows, "windows": windows}
            hooks.setdefault(name, []).append(entry)
    return {"hooks": hooks}


CONFIG_PATH = ".github/hooks/agentseam.json"


# ------------------------------------------------------------------------------
# runtime (agentseam dispatch, specialized to vscode_copilot)

_VOUCH_SPEAKS = True
_WARN_SPEAKS = False
_TRANSFORM_EVENTS = frozenset(('pre_tool',))


def degrade(decision, event):
    """Reduce a decision to what 'vscode_copilot' can actually honor, honestly.

    This is agentseam.dispatch.degrade(), specialized to one fixed agent so this file needs
    no "import agentseam" -- claude_code and vscode_copilot are the only agents with real evidence that an explicit approval word means "skip confirmation"; see agentseam.allow_semantics.
    """
    if decision.outcome == TRANSFORM and event.event not in _TRANSFORM_EVENTS:
        evidence = dict(decision.evidence)
        evidence["degraded_from"] = TRANSFORM
        return Decision.escalate(
            decision.reason or "input requires modification before it can run", evidence=evidence
        )
    if decision.outcome == VOUCH and not _VOUCH_SPEAKS:
        evidence = dict(decision.evidence)
        evidence["degraded_from"] = VOUCH
        return Decision.allow(decision.reason, evidence=evidence, context=decision.context)
    if decision.outcome == WARN and not _WARN_SPEAKS:
        evidence = dict(decision.evidence)
        evidence["degraded_from"] = WARN
        return Decision.allow(decision.reason, evidence=evidence, context=decision.context)
    return decision


# >>> agentseam handler >>>
GUARD_VIOLATION = 1

GUARD_ASK_EXIT = 3

PYTHON_SUFFIX = '.py'

_CRASH_MARKERS = ('traceback (most recent call last)', 'syntax error', 'syntaxerror', 'unexpected eof')

TOOL_UNKNOWN = 'unknown'

ARGV_FALLBACK_ENV = 'CHOCK_ARGV_FALLBACK'

_POSIX_BASH = ('bash', '/bin/bash', '/usr/bin/bash')

_GIT_FOR_WINDOWS = ('C:\\Program Files\\Git', 'C:\\Program Files (x86)\\Git')

_GIT_BASH_DIRS = (('bin',), ('usr', 'bin'))

_BASH_EXE = 'bash.exe'

_WINDOWS_STUB_DIRS = ('/system32/', '/windowsapps/')

_COREUTILS_MARKER = 'sed.exe'

_WINDOWS = 'nt'

_FOUND_BASH = {}

GATE_LOG_ENV = 'CHOCK_GATE_LOG'

_LOG_MAX_BYTES = 1048576

_GUARD_TIMEOUT_SECONDS = 30

GUARD_BLOCKED = 'blocked'

GUARD_CLEAN = 'clean'

GUARD_ASKED = 'asked'

GUARD_UNCHECKED = 'unchecked'

GUARD_ERRORED = 'errored'

VERDICT_DENY = 'deny'

VERDICT_ESCALATE = 'escalate'

def guard_path_from_argv(argv: list[str]) -> _chock_Path | None:
    """The `--guard <path>` argument a vendored runtime was invoked with, or None."""
    if '--guard' in argv:
        i = argv.index('--guard')
        if i + 1 < len(argv):
            return _chock_Path(argv[i + 1])
    return None

def _git_roots() -> list[_chock_Path]:
    """Git for Windows install roots: from `git` on PATH (cmd/ or mingw64/bin/), then the defaults."""
    git = _chock_shutil.which('git')
    near = [_chock_Path(git).parent.parent, _chock_Path(git).parent.parent.parent] if git else []
    return [*near, *(_chock_Path(root) for root in _GIT_FOR_WINDOWS)]

def bash_candidates() -> list[str]:
    """Bash interpreters to try, best first; on Windows Git's own, never the WSL launcher."""
    if _chock_os.name != _WINDOWS:
        return list(_POSIX_BASH)
    found = [str(root.joinpath(*sub, _BASH_EXE)) for root in _git_roots() for sub in _GIT_BASH_DIRS]
    on_path = _chock_shutil.which('bash')
    if on_path and (not any((stub in on_path.lower().replace('\\', '/') for stub in _WINDOWS_STUB_DIRS))):
        found.append(on_path)
    return [c for i, c in enumerate(found) if c not in found[:i] and _chock_Path(c).is_file()]

def interpreter_env(interpreter: str) -> dict[str, str]:
    """The environment a guard runs in: on Windows, Git's usr/bin ahead on PATH for sed and grep."""
    env = dict(_chock_os.environ)
    if _chock_os.name != _WINDOWS:
        return env
    home = _chock_Path(interpreter).parent
    usr_bin = next((d for d in (home.parent / 'usr' / 'bin', home) if (d / _COREUTILS_MARKER).is_file()), None)
    if usr_bin is not None:
        env['PATH'] = str(usr_bin) + _chock_os.pathsep + env.get('PATH', '')
    return env

def find_bash(guard: _chock_Path) -> str | None:
    """First bash that can actually see `guard`, probed once per process; None when none can."""
    if 'bash' in _FOUND_BASH:
        return _FOUND_BASH['bash']
    for candidate in bash_candidates():
        try:
            proc = _chock_subprocess.run([candidate, '-c', f'test -f "{guard.as_posix()}"'], capture_output=True, timeout=10, check=False)
        except (OSError, _chock_subprocess.SubprocessError):
            continue
        if proc.returncode == 0:
            _FOUND_BASH['bash'] = candidate
            return candidate
    return None

def find_interpreter(guard: _chock_Path) -> str | None:
    """The interpreter that can run `guard`: this Python for `.py`, otherwise a usable bash."""
    if guard.suffix == PYTHON_SUFFIX:
        return sys.executable or None
    return find_bash(guard)

def normalize_tool(tool: str | None) -> str:
    """The hook payload's tool name as `bash` | `powershell` | `shell` | `unknown`."""
    name = (tool or '').lower()
    if name in ('powershell', 'pwsh'):
        return 'powershell'
    if name == 'bash':
        return 'bash'
    if name == 'sh' or 'shell' in name:
        return 'shell'
    return TOOL_UNKNOWN

def is_guard_crash(output: str) -> bool:
    """True when a guard's exit-1 output is empty or shows an interpreter crash, not a refusal."""
    lowered = output.lower()
    return not lowered or any((marker in lowered for marker in _CRASH_MARKERS))

def split_command(command: str) -> tuple[list[str], bool]:
    """POSIX `shlex.split` argv, else a whitespace split; the flag is True on the fallback."""
    try:
        return (_chock_shlex.split(command), False)
    except ValueError:
        return (command.split(), True)

def run_guard(guard: _chock_Path, command: str, tool: str='') -> str:
    """`GUARD_BLOCKED` / `GUARD_ASKED` / `GUARD_CLEAN` when the guard ran, otherwise why it did not."""
    return run_guard_detailed(guard, command, tool)[0]

def run_guard_detailed(guard: _chock_Path, command: str, tool: str='') -> tuple[str, str]:
    """`run_guard`'s verdict plus the guard's own first line, which an ask carries to the user."""
    args, fallback = split_command(command)
    if not args:
        return (GUARD_UNCHECKED, '')
    interpreter = find_interpreter(guard)
    if interpreter is None:
        reason = f'no usable bash was found to run {guard.name}; on Windows install Git for Windows (it ships bash), elsewhere put bash on PATH'
        print(f'chock: {reason}', file=sys.stderr)
        return (GUARD_ERRORED, reason)
    try:
        env = {**interpreter_env(interpreter), 'CHOCK_RAW_COMMAND': command, 'CHOCK_TOOL': normalize_tool(tool)}
        if fallback:
            env[ARGV_FALLBACK_ENV] = '1'
        proc = _chock_subprocess.run([interpreter, str(guard), *args], capture_output=True, text=True, encoding='utf-8', errors='replace', env=env, timeout=_GUARD_TIMEOUT_SECONDS, check=False)
    except _chock_subprocess.TimeoutExpired:
        print(f'chock: guard timed out after {_GUARD_TIMEOUT_SECONDS}s, not checked', file=sys.stderr)
        return (GUARD_ERRORED, '')
    except (OSError, UnicodeError) as exc:
        print(f'chock: guard could not run, not checked: {exc}', file=sys.stderr)
        return (GUARD_ERRORED, '')
    output = ((proc.stderr or '') + (proc.stdout or '')).strip()
    first_line = output.splitlines()[0].strip() if output else ''
    if proc.returncode == GUARD_VIOLATION:
        if is_guard_crash(output):
            print(f'chock: guard {_chock_Path(guard).name} exited 1 without a reason (crash?), not checked', file=sys.stderr)
            return (GUARD_ERRORED, '')
        sys.stderr.write(proc.stdout or '')
        sys.stderr.write(proc.stderr or '')
        return (GUARD_BLOCKED, first_line)
    if proc.returncode == GUARD_ASK_EXIT:
        sys.stderr.write(proc.stdout or '')
        sys.stderr.write(proc.stderr or '')
        return (GUARD_ASKED, first_line)
    if proc.returncode != 0:
        print(f'chock: guard exited {proc.returncode}, not checked' + (f': {first_line[:120]}' if first_line else ''), file=sys.stderr)
        return (GUARD_ERRORED, '')
    return (GUARD_CLEAN, '')

def log_outcome(guard: _chock_Path, tool: str, *, verdict: str) -> None:
    """Append one outcome record. Best effort: never raises, never changes the verdict."""
    try:
        if _chock_os.environ.get(GATE_LOG_ENV) == '0':
            return
        guard = guard.resolve()
        if guard.parent.name != 'implementations':
            return
        artifact_root = None
        for parent in guard.parents:
            if (parent / '.chock').is_dir():
                artifact_root = parent / '.chock'
                break
        if artifact_root is None:
            return
        log_dir = artifact_root / 'log'
        log_dir.mkdir(parents=True, exist_ok=True)
        log_path = log_dir / 'gate-events.jsonl'
        if log_path.exists() and log_path.stat().st_size > _LOG_MAX_BYTES:
            log_path.replace(log_dir / 'gate-events.1.jsonl')
        record = {'ts': _chock_datetime.now(_chock_timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ'), 'policy_id': guard.parent.parent.name, 'surface': 'pre-tool-use', 'event': 'tool_use', 'kind': guard.stem, 'tool': tool, 'verdict': verdict}
        with log_path.open('a', encoding='utf-8') as fh:
            fh.write(json.dumps(record, ensure_ascii=False) + '\n')
    except Exception:
        return

def evaluate(argv: list[str], command: str, tool: str='') -> tuple[str, str] | None:
    """Run the guard named on `argv` (`--guard <path>`) against `command`."""
    guard = guard_path_from_argv(argv)
    if guard is None:
        return None
    if not guard.exists():
        return (VERDICT_DENY, f"chock guard {guard} is missing, so this command cannot be checked. Run `chock sync --repo .` to reinstall the policy's guards.")
    verdict, message = run_guard_detailed(guard, command, tool)
    logged = {GUARD_BLOCKED: 'block', GUARD_ASKED: 'ask', GUARD_CLEAN: 'allow'}
    if verdict in logged:
        log_outcome(guard, tool, verdict=logged[verdict])
    if verdict == GUARD_BLOCKED:
        return (VERDICT_DENY, f'Blocked by chock policy: {guard.stem}')
    if verdict == GUARD_ASKED:
        return (VERDICT_ESCALATE, f'chock policy {guard.stem} asks before this runs: {message}' if message else f'chock policy {guard.stem} asks for confirmation before this runs (guard gave no reason).')
    if verdict == GUARD_ERRORED:
        why = message or f"the {guard.stem} guard did not complete (see this hook's stderr)"
        return (VERDICT_ESCALATE, f'chock could not check this command against {guard.stem}: {why}. Approving runs it unchecked.')
    return None

_EDIT_KEYS = (('old_string', 'new_string'), ('oldString', 'newString'), ('old_str', 'new_str'))

_EDIT_LIST = 'edits'

_CRLF = '\r\n'

def _edit_call_input(event):
    raw = getattr(event, 'raw', None)
    tool_input = raw.get('tool_input') if isinstance(raw, dict) else None
    if isinstance(tool_input, str) and tool_input[:1] == '{':
        try:
            tool_input = json.loads(tool_input)
        except ValueError:
            return {}
    return tool_input if isinstance(tool_input, dict) else {}

def _pair(item):
    if not isinstance(item, dict):
        return None
    for old, new in _EDIT_KEYS:
        if isinstance(item.get(old), str) and isinstance(item.get(new), str):
            return (item[old], item[new], item.get('replace_all') is True)
    return None

def edit_replacements(event):
    """The (old, new, replace_all) replacements an edit call applies, in order; None if not an edit."""
    tool_input = _edit_call_input(event)
    listed = tool_input.get(_EDIT_LIST)
    found = [_pair(item) for item in (listed if isinstance(listed, list) else [tool_input])]
    if not found or None in found:
        return None
    return found

def _replace(text, old, new, every):
    """`text` with the replacement applied, or None when `old` is not there to replace.

    The file is read with universal newlines, so a CRLF file (a Windows checkout) arrives as
    LF; the call's strings are brought to LF too, whichever ending the client sent them with,
    rather than calling a real edit a failure over line endings.
    """
    old, new = (old.replace(_CRLF, '\n'), new.replace(_CRLF, '\n'))
    if old == '':
        return new if text == '' else None
    if old not in text:
        return None
    return text.replace(old, new) if every else text.replace(old, new, 1)

def edited_text(event, root=None):
    """The file an edit call would leave behind, or None when it is not an edit or cannot be rebuilt."""
    replacements = edit_replacements(event)
    path = getattr(event, 'path', None)
    if replacements is None or not path:
        return None
    target = _chock_Path(path)
    if not target.is_absolute():
        target = _chock_Path(root if root is not None else _chock_Path.cwd()) / target
    try:
        text = target.read_text(encoding='utf-8') if target.exists() else ''
    except (OSError, UnicodeDecodeError):
        return None
    for old, new, every in replacements:
        text = _replace(text, old, new, every)
        if text is None:
            return None
    return text

def added_from_event(event):
    """What an edit call introduces -- what `added_lines` means for it -- or {} for any other call."""
    replacements = edit_replacements(event)
    path = getattr(event, 'path', None)
    if replacements is None or not path:
        return {}
    return {str(path): '\n'.join((new for _, new, _ in replacements))}

_BEGIN = '*** Begin Patch'

_END = '*** End Patch'

_ADD = '*** Add File: '

_DELETE = '*** Delete File: '

_UPDATE = '*** Update File: '

_MOVE = '*** Move to: '

_EOF = '*** End of File'

_HUNK = '@@'

_OPS = (('add', _ADD), ('delete', _DELETE), ('update', _UPDATE))

def patch_text(event):
    """The patch an apply_patch call carries, from its first to its last marker; None otherwise."""
    raw = getattr(event, 'raw', None)
    tool_input = raw.get('tool_input') if isinstance(raw, dict) else None
    command = tool_input.get('command') if isinstance(tool_input, dict) else None
    if isinstance(command, list):
        command = '\n'.join((part for part in command if isinstance(part, str)))
    start = command.find(_BEGIN) if isinstance(command, str) else -1
    end = command.find(_END, start) if start >= 0 else -1
    return command[start:end + len(_END)] if end >= 0 else None

def _body_line(current, line):
    """Add one line under the file operation `current` is reading."""
    if line.startswith(_MOVE):
        current[2] = line[len(_MOVE):].strip()
    elif line.startswith(_HUNK):
        current[3].append([line[len(_HUNK):].strip(), [], False])
    elif line.startswith(_EOF):
        if current[3]:
            current[3][-1][2] = True
    elif current[0] == 'add':
        current[3].append(line[1:] if line.startswith('+') else line)
    else:
        if not current[3]:
            current[3].append(['', [], False])
        current[3][-1][1].append(line if line[:1] in (' ', '-', '+') else ' ' + line)

def parse_patch(patch):
    """[(op, path, moved_to, hunks)]: op is add/delete/update; a hunk is (anchor, lines, at_eof)."""
    operations = []
    for line in patch.replace('\r\n', '\n').split('\n')[1:]:
        if line.startswith(_END):
            break
        opened = next(((op, marker) for op, marker in _OPS if line.startswith(marker)), None)
        if opened is not None:
            operations.append([opened[0], line[len(opened[1]):].strip(), None, []])
        elif operations:
            _body_line(operations[-1], line)
    return [tuple(operation) for operation in operations]

def _find(lines, wanted, start):
    """Where `wanted` starts in `lines` at or after `start`, exactly or ignoring trailing space."""
    for loose in (False, True):
        for index in range(start, len(lines) - len(wanted) + 1):
            window = lines[index:index + len(wanted)]
            if window == wanted or (loose and [w.rstrip() for w in window] == [w.rstrip() for w in wanted]):
                return index
    return None

def apply_hunks(text, hunks):
    """`text` with the hunks applied in order, or None when one cannot be placed."""
    lines = text.split('\n')
    cursor = 0
    for anchor, body, at_eof in hunks:
        if anchor:
            found = _find(lines, [anchor], cursor)
            if found is None:
                found = next((i for i in range(cursor, len(lines)) if anchor.strip() in lines[i]), None)
            if found is None:
                return None
            cursor = found + 1
        old = [line[1:] for line in body if line[:1] in (' ', '-')]
        new = [line[1:] for line in body if line[:1] in (' ', '+')]
        if not old:
            at = len(lines) - (1 if lines and lines[-1] == '' else 0) if at_eof else cursor
        else:
            at = _find(lines, old, cursor)
            if at is None:
                return None
        lines[at:at + len(old)] = new
        cursor = at + len(new)
    return '\n'.join(lines)

def _read(root, path):
    target = _chock_Path(path)
    if not target.is_absolute():
        target = _chock_Path(root if root is not None else _chock_Path.cwd()) / target
    try:
        return target.read_text(encoding='utf-8')
    except (OSError, UnicodeDecodeError):
        return None

def patched_files(event, root=None):
    """{path: text} for every file an apply_patch call adds or updates and can be rebuilt."""
    patch = patch_text(event)
    if patch is None:
        return {}
    files = {}
    for op, path, moved_to, body in parse_patch(patch):
        if op == 'add':
            files[path] = '\n'.join(body) + '\n'
        elif op == 'update':
            before = _read(root, path)
            after = apply_hunks(before, body) if before is not None else None
            if after is not None:
                files[moved_to or path] = after
    return files

def patch_added(event):
    """{path: the lines the patch adds}, which is what `added_lines` means for it."""
    patch = patch_text(event)
    if patch is None:
        return {}
    added = {}
    for op, path, moved_to, body in parse_patch(patch):
        if op == 'add':
            added[path] = '\n'.join(body)
        elif op == 'update':
            added[moved_to or path] = '\n'.join((line[1:] for _, hunk, _ in body for line in hunk if line[:1] == '+'))
    return added

GATE_BLOCKED = 'blocked'

GATE_CLEAN = 'clean'

GATE_ERRORED = 'errored'

GATE_ASKED = 'asked'

GATE_WARNED = 'warned'

VERDICT_WARN = 'warn'

_EXIT_OUTCOME = {0: GATE_CLEAN, 1: GATE_BLOCKED, 3: GATE_ASKED, 4: GATE_WARNED}

def runner_outcome(returncode, stderr):
    """(outcome, message) for the runner's exit code and stderr: its words, only when it refused or spoke."""
    outcome = _EXIT_OUTCOME.get(returncode, GATE_ERRORED)
    return (outcome, '' if outcome == GATE_CLEAN else (stderr or '').strip())

def gate_decision(outcome, message, gate):
    """The decision an outcome earns, or None when the gate allowed: deny, escalate (ask) or warn."""
    policy = gate.parent.parent.name
    spoken = {GATE_BLOCKED: (VERDICT_DENY, message or f'Blocked by chock policy: {policy}'), GATE_ASKED: (VERDICT_ESCALATE, message or f'Chock policy {policy} asks before this write.'), GATE_WARNED: (VERDICT_WARN, message or f'Chock policy {policy} warns about this write.'), GATE_ERRORED: (VERDICT_DENY, f'chock could not check this write: {message}. Refusing rather than reporting an allow it never established.')}
    return spoken.get(outcome)

OUTSIDE_KEY = 'outside_repo'

_UP = '..'

_DRIVE_AT = 1

_SEPARATORS = ('/', '\\')

def _slashed(path):
    return str(path).replace('\\', '/')

def is_outside(path):
    """Whether a path as the runtime names it lies outside the repository: absolute, or climbing out."""
    text = _slashed(path)
    return text.startswith(('/', _UP + '/')) or text[_DRIVE_AT:_DRIVE_AT + 1] == ':' or text == _UP

def expand_home(pattern):
    """`~` (alone or before a separator) as this machine's home directory; anything else as given."""
    text = str(pattern)
    if text[:1] == '~' and (len(text) == 1 or text[1] in _SEPARATORS):
        return _chock_os.path.expanduser('~') + text[1:]
    return text

def _outside_fold(path):
    """`path` with `.` and `..` folded lexically and doubled slashes dropped; a root's leading slash kept."""
    parts = []
    for part in _slashed(path).split('/'):
        if part == _UP and parts and (parts[-1] not in ('', _UP)):
            parts.pop()
        elif part != '.' and (part or not parts):
            parts.append(part)
    return '/'.join(parts)

def declared_outside(path, root, patterns, *, windows=None):
    """The absolute, slash-separated path when it is outside `root` and matches a declared glob; else None."""
    windows = _chock_os.name == 'nt' if windows is None else windows
    text = _slashed(path)
    if not is_outside(text) or not patterns:
        return None
    absolute = text if not text.startswith(_UP) else _slashed(root) + '/' + text
    absolute = _outside_fold(absolute)
    subject = absolute.lower() if windows else absolute
    for pattern in patterns:
        wanted = _outside_fold(expand_home(pattern))
        if _chock_fnmatch.fnmatchcase(subject, wanted.lower() if windows else wanted):
            return absolute
    return None

def outside_globs(gate):
    """The `outside_repo` globs the compiled gate declares; none when it declares none or cannot be read."""
    try:
        declared = json.loads(gate.read_text(encoding='utf-8')).get(OUTSIDE_KEY)
    except (OSError, ValueError, AttributeError):
        return []
    return [g for g in declared if isinstance(g, str)] if isinstance(declared, list) else []

def judged_files(files, root, patterns, repo_names):
    """`files` ({path: text}) keyed the way a gate judges them.

    A path inside the repository is named by `repo_names(path)`; one outside is kept, under its
    absolute path, only when a declared glob matches it.
    """
    kept = {}
    for path, text in files.items():
        for name in repo_names(path):
            if not is_outside(name):
                kept[name] = text
                continue
            found = declared_outside(name, root, patterns)
            if found is not None:
                kept[found] = text
    return kept

SESSION_MAX_ENTRIES = 500

SESSION_PRUNE_SECONDS = 7 * 24 * 3600

SESSION_FIELD_CAP = 300

SESSION_TRIM_BYTES = 131072

SESSION_DEDUPE_TAIL = 8

SESSION_STATE_PARTS = ('.chock', 'state')

SESSION_INPUT_KEYS = ('tool_input', 'toolInput', 'toolArgs', 'input')

SESSION_PATH_KEYS = ('file_path', 'filePath', 'path', 'notebook_path', 'target_file', 'TargetFile')

SESSION_URL_KEYS = ('url', 'uri')

SESSION_RESPONSE_KEYS = ('tool_response', 'toolResponse', 'tool_result', 'toolResult')

SESSION_UNKNOWN_ID = 'unknown'

SESSION_ID_MAX = 128

SESSION_MASK = '***'

def tool_call_input(event):
    """The tool's arguments as a dict, decoding the JSON-string form some vendors send; {} when absent."""
    raw = getattr(event, 'raw', None)
    if not isinstance(raw, dict):
        return {}
    for key in SESSION_INPUT_KEYS:
        value = raw.get(key)
        if isinstance(value, str) and value[:1] == '{':
            try:
                value = json.loads(value)
            except ValueError:
                continue
        if isinstance(value, dict):
            return value
    return {}

def session_id_of(event):
    """The session id as a safe file stem: separators and leading dots removed, never empty."""
    raw = getattr(event, 'raw', None) or {}
    given = getattr(event, 'session_id', None) or (raw.get('session_id') if isinstance(raw, dict) else None)
    stem = ''.join((c for c in str(given or '') if c.isalnum() or c in '._-')).lstrip('.')
    return stem[:SESSION_ID_MAX] or SESSION_UNKNOWN_ID

def session_log_path(root, session_id):
    return _chock_Path(root).joinpath(*SESSION_STATE_PARTS, session_id + '.jsonl')

def session_for(event, root):
    """What a script gate receives as `session`: the id, the log's absolute path, this call's id."""
    session_id = session_id_of(event)
    return {'id': session_id, 'log_path': session_log_path(root, session_id).as_posix(), 'tool_use_id': getattr(event, 'tool_use_id', None)}

def _mask_assignments(command):
    """`command` with the value of every `NAME=value` word masked: an env prefix is a secret's usual home."""
    words = []
    for word in command.split(' '):
        name, eq, _ = word.partition('=')
        words.append(name + eq + SESSION_MASK if eq and name.isidentifier() else word)
    return ' '.join(words)

def _bare_url(url):
    """`url` without userinfo, query and fragment: where a token or a secret is usually carried."""
    url = url.split('#', 1)[0].split('?', 1)[0]
    scheme, sep, rest = url.partition('://')
    if not sep:
        return url
    authority, slash, tail = rest.partition('/')
    return scheme + sep + authority.rsplit('@', 1)[-1] + slash + tail

def _first_str(mapping, keys):
    for key in keys:
        value = mapping.get(key)
        if isinstance(value, str) and value:
            return value
    return None

def session_summary(event):
    """The input of a tool call as {path?, command?, url?}: what a policy asks about, nothing else."""
    tool_input = tool_call_input(event)
    path = getattr(event, 'path', None) or _first_str(tool_input, SESSION_PATH_KEYS)
    command = getattr(event, 'command', None) or _first_str(tool_input, ('command',))
    url = _first_str(tool_input, SESSION_URL_KEYS)
    summary = {}
    if isinstance(path, str) and path:
        summary['path'] = path[:SESSION_FIELD_CAP]
    if isinstance(command, str) and command:
        summary['command'] = _mask_assignments(command.splitlines()[0] if command.strip() else '')[:SESSION_FIELD_CAP]
    if url:
        summary['url'] = _bare_url(url)[:SESSION_FIELD_CAP]
    return summary

def _response_failed(response):
    if not isinstance(response, dict):
        return False
    if response.get('is_error') is True or response.get('isError') is True or response.get('success') is False:
        return True
    code = response.get('exit_code', response.get('exitCode'))
    return bool(response.get('error')) or (isinstance(code, int) and code != 0)

def session_outcome(event):
    """`ok` or `error` for a finished call, from what the payload says; None before it ran."""
    if event.event == 'tool_failure':
        return 'error'
    if event.event != 'post_tool':
        return None
    raw = getattr(event, 'raw', None) or {}
    failed = any((_response_failed(raw.get(key)) for key in SESSION_RESPONSE_KEYS)) if isinstance(raw, dict) else False
    return 'error' if failed else 'ok'

def _same_call(line, record):
    """Whether `line` is `record` already logged: same call id, or, with none, the same second and input."""
    try:
        seen = json.loads(line)
    except ValueError:
        return False
    if seen.get('phase') != record['phase']:
        return False
    if record['tool_use_id']:
        return seen.get('tool_use_id') == record['tool_use_id']
    return not seen.get('tool_use_id') and all((seen.get(key) == record[key] for key in ('ts', 'tool', 'input', 'outcome')))

def _prune_old(directory):
    cutoff = _chock_datetime.now(_chock_timezone.utc).timestamp() - SESSION_PRUNE_SECONDS
    for old in directory.glob('*.jsonl'):
        try:
            if old.stat().st_mtime < cutoff:
                old.unlink()
        except OSError:
            continue

def _append_bounded(path, line, record):
    lines = path.read_text(encoding='utf-8', errors='replace').splitlines() if path.exists() else []
    if any((_same_call(seen, record) for seen in lines[-SESSION_DEDUPE_TAIL:])):
        return
    if len(lines) < SESSION_MAX_ENTRIES and path.exists() and (path.stat().st_size < SESSION_TRIM_BYTES):
        with path.open('a', encoding='utf-8') as fh:
            fh.write(line + '\n')
        return
    kept = [*lines, line][-SESSION_MAX_ENTRIES:]
    scratch = path.with_suffix('.tmp')
    scratch.write_text('\n'.join(kept) + '\n', encoding='utf-8')
    scratch.replace(path)

def session_record(root, event, phase, outcome=None):
    """Append one record for this call to its session's log. Best effort: never raises."""
    try:
        path = session_log_path(root, session_id_of(event))
        path.parent.mkdir(parents=True, exist_ok=True)
        record = {'ts': _chock_datetime.now(_chock_timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ'), 'session_id': path.stem, 'phase': phase, 'tool': str(getattr(event, 'tool', None) or ''), 'input': session_summary(event), 'outcome': outcome, 'tool_use_id': getattr(event, 'tool_use_id', None)}
        _append_bounded(path, json.dumps(record, ensure_ascii=False, sort_keys=True), record)
        _prune_old(path.parent)
    except Exception:
        return

GATE_FLAG = '--gate'

_GATE_TIMEOUT_SECONDS = 30

_GATE_DEPTH_TO_CHOCK = 3

_RUNNER_PARTS = ('bin', 'gate.py')

_PACKAGED_RUNNER = 'gate.py'

_GIT = 'git'

_UTF8 = 'utf-8'

_PATH_ERRORS = 'surrogateescape'

_PARENT = '..'

_DRIVE_COLON = ':'

_DELETED = 'D'

_RENAMED = 'R'

VERDICT_DENY = 'deny'

def gate_path_from_argv(argv):
    """The `--gate <path>` argument a vendored runtime was invoked with, or None."""
    if GATE_FLAG in argv:
        index = argv.index(GATE_FLAG)
        if index + 1 < len(argv):
            return _chock_Path(argv[index + 1])
    return None

def runner_for(gate):
    """The gate runner: beside the gate in a plugin, under .chock/bin in a repository, else None."""
    packaged = gate.resolve().parent / _PACKAGED_RUNNER
    if packaged.exists():
        return packaged
    parents = gate.resolve().parents
    if len(parents) <= _GATE_DEPTH_TO_CHOCK:
        return None
    runner = parents[_GATE_DEPTH_TO_CHOCK].joinpath(*_RUNNER_PARTS)
    return runner if runner.exists() else None

def writes_from_event(event, root=None):
    """The one file this tool call would write, or none when it carries no file text.

    An edit call carries only the text it inserts; judged alone, that fragment has no imports,
    no class and no neighbours, so a gate that reads a whole file (a script kind) finds nothing
    in it. An edit is therefore judged as the file it would leave: the file on disk with the
    call's replacements applied. When that cannot be rebuilt -- the file is unreadable, or the
    text to replace is not in it, so the call itself will fail -- the fragment is judged as
    before and the turn's end judges what actually landed. A Codex apply_patch call names its
    files only inside the patch; each one it adds or updates is judged as the patch leaves it.
    """
    patched = patched_files(event, root)
    if patched:
        return patched
    path = getattr(event, 'path', None)
    content = getattr(event, 'content', None)
    edited = edited_text(event, root)
    if path and edited is not None:
        return {str(path): edited}
    if not path or not isinstance(content, str):
        return {}
    return {str(path): content}

def _folded(pure):
    """`pure` with `..` folded lexically; an absolute path never climbs above its anchor."""
    parts = []
    for part in pure.parts:
        if part != _PARENT:
            parts.append(part)
        elif len(parts) > 1:
            parts.pop()
    return type(pure)(*parts)

def repo_relative(path, root):
    """`path` relative to `root` in POSIX form, as scope globs are written; as given when outside `root`."""
    text = str(path)
    if root is None:
        return text
    windows = _chock_os.name == 'nt' or str(root)[1:2] == _DRIVE_COLON
    flavour = _chock_PureWindowsPath if windows else _chock_PurePosixPath
    try:
        return _folded(flavour(str(root)) / text).relative_to(flavour(str(root))).as_posix()
    except ValueError:
        pass
    if windows != (_chock_os.name == 'nt'):
        return text
    try:
        return _chock_Path(root, text).resolve().relative_to(_chock_Path(root).resolve()).as_posix()
    except (OSError, ValueError, RuntimeError):
        return text

def repo_paths(path, root):
    """Every repo-relative name a write is judged under: as written, and through symlinks and case."""
    lexical = repo_relative(path, root)
    if root is None or (str(root)[1:2] == _DRIVE_COLON) != (_chock_os.name == 'nt'):
        return (lexical,)
    try:
        resolved = _chock_Path(root, str(path)).resolve().relative_to(_chock_Path(root).resolve()).as_posix()
    except (OSError, ValueError, RuntimeError):
        return (lexical,)
    return tuple(dict.fromkeys((lexical, resolved)))

def changed_paths(repo_root):
    """Every uncommitted path in the worktree. Outside a repository there is nothing to list."""
    try:
        proc = _chock_subprocess.run([_GIT, '-C', str(repo_root), 'status', '--porcelain=v1', '--untracked-files=all', '-z'], capture_output=True, text=True, encoding=_UTF8, errors=_PATH_ERRORS, timeout=_GATE_TIMEOUT_SECONDS, check=False)
    except (OSError, _chock_subprocess.SubprocessError):
        return []
    if proc.returncode != 0:
        return []
    fields = [field for field in (proc.stdout or '').split('\x00') if field]
    paths = []
    skip_next = False
    for field in fields:
        if skip_next:
            skip_next = False
            continue
        status, path = (field[:2], field[3:])
        skip_next = status.startswith(_RENAMED)
        if _DELETED in status or not path:
            continue
        paths.append(path)
    return paths

def writes_from_worktree(repo_root):
    """What this turn actually left on disk, however it was written.

    The write path sees only writes it recognises; a shell heredoc carries no file argument.
    Reading final state is what makes that stop mattering, so this deliberately does not care
    which tool produced the bytes.
    """
    writes = {}
    for path in changed_paths(repo_root):
        try:
            writes[path] = _chock_Path(repo_root, path).read_text(encoding='utf-8')
        except (OSError, UnicodeDecodeError):
            continue
    return writes

def run_gate(gate, writes, event, root=None, extra=None):
    """Ask the vendored runner. Returns (outcome, message) and never decides for itself.

    `extra` adds stdin keys: `added` (per edited path, only the text the edit introduces; a runner
    that predates it judges the whole file, which only ever refuses more) and the script `session`.
    """
    runner = runner_for(gate)
    if runner is None:
        return (GATE_ERRORED, 'the vendored gate runner is not installed beside this gate')
    try:
        proc = _chock_subprocess.run([sys.executable, str(runner), 'run', '--gate', str(gate), '--event', event], input=json.dumps({'writes': writes, **(extra or {})}), capture_output=True, text=True, encoding=_UTF8, errors='replace', timeout=_GATE_TIMEOUT_SECONDS, check=False, cwd=str(root) if root is not None else None)
    except (OSError, _chock_subprocess.SubprocessError) as exc:
        return (GATE_ERRORED, str(exc))
    return runner_outcome(proc.returncode, proc.stderr)

_EVENT_ARG = {'pre_tool': 'pre-tool-use', 'stop': 'stop'}

PRE_TOOL = 'pre_tool'

def root_for(gate):
    """The repository this compiled gate belongs to, or None when the layout is not that."""
    parents = gate.resolve().parents
    if len(parents) <= _GATE_DEPTH_TO_CHOCK:
        return None
    if parents[_GATE_DEPTH_TO_CHOCK - 1].name != 'compiled' or parents[_GATE_DEPTH_TO_CHOCK].name != '.chock':
        return None
    return parents[_GATE_DEPTH_TO_CHOCK].parent

def repo_root_for(event, gate):
    """The repository under judgement: the compiled layout's root, else where the agent works."""
    root = root_for(gate)
    if root is not None:
        return root
    cwd = getattr(event, 'cwd', None)
    return _chock_Path(cwd) if cwd else _chock_Path.cwd()

def writes_for(event, gate):
    """What this event puts under judgement: the call's own text, or what the turn left behind."""
    if event.event == PRE_TOOL:
        return writes_from_event(event, repo_root_for(event, gate))
    if _reentered(event):
        return {}
    return writes_from_worktree(repo_root_for(event, gate))

def _reentered(event):
    """Whether this stop re-entered its own hook: Claude Code's `stop_hook_active`, Cursor's `loop_count`."""
    raw = event.raw or {}
    return bool(raw.get('stop_hook_active') or raw.get('loop_count'))

def _missing_gate(gate, event):
    """A gate the hook names but that is not on disk: a broken install, so a refusal that says so."""
    if event.event != PRE_TOOL and _reentered(event):
        return None
    return (VERDICT_DENY, f'chock gate {gate} is missing, so this write cannot be checked. Run `chock sync --repo .` to rebuild the compiled gates.')

def evaluate_gate(argv, event):
    """The decision this event earns from a compiled gate, or None when it has nothing to say."""
    gate = gate_path_from_argv(argv)
    name = _EVENT_ARG.get(getattr(event, 'event', ''))
    if gate is None or name is None:
        return None
    if not gate.exists():
        return _missing_gate(gate, event)
    root = repo_root_for(event, gate)
    outside = outside_globs(gate)
    writes = judged_files(writes_for(event, gate), root, outside, lambda path: repo_paths(path, root))
    if not writes:
        return None
    added = {**patch_added(event), **added_from_event(event)} if event.event == PRE_TOOL else {}
    added = judged_files(added, root, outside, lambda path: repo_paths(path, root))
    added = {path: text for path, text in added.items() if path in writes}
    extra = {**({'added': added} if added else {}), 'session': session_for(event, root)}
    outcome, message = run_gate(gate, writes, name, root, extra)
    return gate_decision(outcome, message, gate)

TOOL_CALL_FLAG = '--tool-call'

RECORD_FLAG = '--record'

TOOL_CALL_EVENT = 'tool_call'

_TOOL_CALL_PRE = 'pre_tool'

_TOOL_CALL_POST = ('post_tool', 'tool_failure')

_TOOL_CALL_TIMEOUT_SECONDS = 30

_TOOL_CALL_SCRIPT_KIND = 'script'

_TOOL_CALL_REGEX_KIND = 'content_regex'

_TOOL_CALL_BLOCKED = 'blocked'

_TOOL_CALL_NEEDS_SESSION = frozenset({_TOOL_CALL_SCRIPT_KIND})

_TOOL_CALL_EXIT_VERDICTS = {0: None, 1: 'deny', 3: 'escalate', 4: 'warn'}

_TOOL_CALL_CEILING = {'block': 'deny', 'ask': 'escalate', 'warn': 'warn'}

_TOOL_CALL_RANK = {'warn': 0, 'escalate': 1, 'deny': 2}

_TOOL_CALL_UNDECIDED = ' -- refusing rather than allowing what it never judged'

def _flag_path(argv, flag):
    if flag in argv:
        index = argv.index(flag)
        if index + 1 < len(argv):
            return _chock_Path(argv[index + 1])
    return None

def tool_call_matches(globs, tool):
    """Whether `tool` (a tool name, exact case) matches any glob; no globs match nothing."""
    return any((_chock_fnmatch.fnmatchcase(tool, str(glob)) for glob in globs))

def _tool_call_refusal(spec, spoken):
    return spoken or str(spec.get('message') or '').strip() or 'blocked by a chock tool_call gate'

def _tool_call_regex(spec, tool_input):
    """`deny` verdict when the input, as JSON text, matches the gate's `content_pattern`."""
    text = json.dumps(tool_input, sort_keys=True, ensure_ascii=False)
    if _chock_re.search(str((spec.get('params') or {}).get('content_pattern', '')), text):
        return ('deny', _tool_call_refusal(spec, ''))
    return None

def _tool_call_script(spec, root, payload):
    """Run the policy's script on `payload`; a missing script, crash or timeout refuses."""
    named = str((spec.get('params') or {}).get('script', ''))
    script = _chock_Path(root) / named
    if not script.is_file():
        return ('deny', f'script gate: {named!r} is not installed{_TOOL_CALL_UNDECIDED}')
    try:
        proc = _chock_subprocess.run([sys.executable, str(script)], input=json.dumps(payload), capture_output=True, text=True, encoding='utf-8', errors='replace', cwd=str(root), timeout=_TOOL_CALL_TIMEOUT_SECONDS, check=False)
    except _chock_subprocess.TimeoutExpired:
        budget = f'gave no verdict within {_TOOL_CALL_TIMEOUT_SECONDS}s'
        return ('deny', f'script gate: {script.name} {budget}{_TOOL_CALL_UNDECIDED}')
    except OSError as exc:
        return ('deny', f'script gate: {script.name} could not run ({exc}){_TOOL_CALL_UNDECIDED}')
    spoken = ((proc.stderr or '') + (proc.stdout or '')).strip()
    if proc.returncode in _TOOL_CALL_EXIT_VERDICTS:
        verdict = _TOOL_CALL_EXIT_VERDICTS[proc.returncode]
        return None if verdict is None else (verdict, spoken or f'blocked by {script.name}')
    first = spoken.splitlines()[0] if spoken else ''
    detail = f': {first}' if first else ''
    return ('deny', f'script gate: {script.name} exited {proc.returncode}{detail}{_TOOL_CALL_UNDECIDED}')

def _tool_call_verdict(spec, root, event):
    """None to allow, else (verdict, message) for this call; a kind a tool call cannot answer refuses."""
    tool, tool_input = (str(event.tool or ''), tool_call_input(event))
    kind = spec.get('kind')
    if kind == _TOOL_CALL_REGEX_KIND:
        return _tool_call_regex(spec, tool_input)
    if kind == _TOOL_CALL_SCRIPT_KIND:
        payload = {'event': TOOL_CALL_EVENT, 'repo_root': str(root), 'tool': tool, 'input': tool_input, 'session': session_for(event, root)}
        return _tool_call_script(spec, root, payload)
    return ('deny', f'chock tool_call gate: kind {kind!r} cannot judge a tool call{_TOOL_CALL_UNDECIDED}')

def _tool_call_capped(spec, verdict):
    """`verdict` held to the gate's declared action; an unknown action keeps the verdict as spoken."""
    ceiling = _TOOL_CALL_CEILING.get(spec.get('action', 'block'))
    if verdict is None or ceiling is None:
        return verdict
    return (min(verdict[0], ceiling, key=_TOOL_CALL_RANK.__getitem__), verdict[1])

def _tool_call_spec(gate):
    """The compiled gate as a dict, or (None, refusal) when the install is broken."""
    if not gate.exists():
        return (None, f'chock gate {gate} is missing, so this tool call cannot be checked. Run `chock sync --repo .` to rebuild the compiled gates.')
    try:
        return (json.loads(gate.read_text(encoding='utf-8')), None)
    except (OSError, ValueError) as exc:
        return (None, f'chock could not read {gate}: {exc}. Refusing rather than reporting an allow it never established.')

def evaluate_tool_call(argv, event):
    """The decision a tool_call gate earns this call, or None; also logs the call for the session.

    `--tool-call <gate>` judges a PreToolUse call and, for a gate whose check reads the session,
    logs it after the verdict, so the script reads prior calls only. `--record <gate>` logs what
    a call came to, after it ran (a vendor's PostToolUse and failure events).
    """
    recording = _flag_path(argv, RECORD_FLAG)
    if recording is not None:
        if event.event in _TOOL_CALL_POST:
            session_record(repo_root_for(event, recording), event, 'post', session_outcome(event))
        return None
    gate = _flag_path(argv, TOOL_CALL_FLAG)
    if gate is None or event.event != _TOOL_CALL_PRE:
        return None
    spec, broken = _tool_call_spec(gate)
    if spec is None:
        return ('deny', broken)
    root = repo_root_for(event, gate)
    verdict = None
    if TOOL_CALL_EVENT in spec.get('on', []) and tool_call_matches((spec.get('params') or {}).get('tools', []), str(event.tool or '')):
        verdict = _tool_call_capped(spec, _tool_call_verdict(spec, root, event))
    if spec.get('kind') in _TOOL_CALL_NEEDS_SESSION:
        session_record(root, event, 'pre', _TOOL_CALL_BLOCKED if verdict and verdict[0] == 'deny' else None)
    return verdict


def _spoken(verdict):
    outcome, reason = verdict
    if outcome == VERDICT_WARN:
        return Decision.warn(reason)
    return Decision.escalate(reason) if outcome == ESCALATE else Decision.deny(reason)


def _judge(event):
    if event.event == "pre_tool" and event.command:
        verdict = evaluate(sys.argv[1:], event.command, event.tool or "")
        if verdict is not None:
            outcome, reason = verdict
            return Decision.escalate(reason) if outcome == ESCALATE else Decision.deny(reason)
    gated = evaluate_gate(sys.argv[1:], event)
    if gated is not None:
        return _spoken(gated)
    called = evaluate_tool_call(sys.argv[1:], event)
    if called is not None:
        return _spoken(called)
    return None


def handle(event):
    # A door that cannot decide refuses. An exception escaping here would exit the hook
    # with a traceback, which every client reads as a non-blocking error: fail-open, with
    # the reason on a stderr nobody watches. The refusal carries the reason instead.
    try:
        return _judge(event)
    except Exception as exc:  # noqa: BLE001 -- any failure here must refuse, never fall through
        return Decision.deny(
            "chock could not check this call (%s: %s). Refusing rather than reporting an "
            "allow it never established." % (type(exc).__name__, exc)
        )


def _chock_copilot_respond(decision, event):
    # Copilot's own runtime answered a top-level deny and a top-level Stop block in live probes
    # (VS Code agent mode, 2026-09-28); which of the top-level and nested Stop blocks it reads was
    # never isolated. The nested answer agentseam writes stays, and the witnessed top-level one
    # is added beside it, so either reading refuses.
    text, code = respond(decision, event)
    if not text:
        return text, code
    body = json.loads(text)
    nested = body.get("hookSpecificOutput")
    if not isinstance(nested, dict):
        return text, code
    if event.event == PRE_TOOL and nested.get("permissionDecision") == "deny":
        body["permissionDecision"] = nested["permissionDecision"]
        body["permissionDecisionReason"] = nested.get("permissionDecisionReason")
    elif event.event == STOP and nested.get("decision") == "block":
        body["decision"] = nested["decision"]
        body["reason"] = nested.get("reason")
    return json.dumps(body), code
# <<< agentseam handler <<<


def _coerce(result):
    if result is None:
        return Decision.allow()
    if isinstance(result, Decision):
        return result
    raise TypeError("handle() must return a Decision or None, got %r" % (type(result),))


def _read_payload(stream):
    # Decode bytes ourselves rather than trust the platform locale -- a BOM'd or non-UTF-8
    # stdin must not silently disable the gate. See agentseam.dispatch for the incident
    # this guards: a Windows console's cp1252 layer turning a UTF-8 BOM into three bytes
    # json cannot parse, with the hook allowing everything while claiming enforcement.
    buffer = getattr(stream, "buffer", None)
    if buffer is not None:
        return buffer.read().decode("utf-8-sig", errors="replace")
    return stream.read().lstrip("\ufeff")


def _emit(out, text):
    buffer = getattr(out, "buffer", None)
    if buffer is not None:
        buffer.write(text.encode("utf-8"))
        buffer.flush()
    else:
        out.write(text)
        out.flush()


def _report(text):
    # Best effort, never raising: a diagnostic must not pre-empt the refusal it accompanies.
    # A hook's stderr is whatever the host gave it -- closed (then sys.stderr is None, and
    # the traceback module's default print would land on STDOUT, inside the verdict), a
    # console code page that cannot hold the payload text quoted in the exception, a pipe
    # nobody reads.
    try:
        sys.stderr.write(text)
        sys.stderr.flush()
    except Exception:
        return


_STDERR_FD = 2


def _divert_fd1():
    """Point fd 1 at stderr (devnull if there is none); the saved fd 1, or None if it could not."""
    try:
        saved = os.dup(1)
    except OSError:
        return None
    # With fd 2 closed, dup() hands back 2 itself, and "stderr" would be stdout again.
    if saved > _STDERR_FD:
        with contextlib.suppress(OSError):
            os.dup2(_STDERR_FD, 1)
            return saved
    sink = os.open(os.devnull, os.O_WRONLY)
    os.dup2(sink, 1)
    os.close(sink)
    return saved


def _flush(streams):
    """Flush each stream that exists; a broken one is no reason to lose the verdict."""
    for stream in streams:
        if stream is not None:
            with contextlib.suppress(Exception):
                stream.flush()


@contextlib.contextmanager
def _stdout_to_stderr():
    # Stdout is the verdict channel. A handler's stray print (or a child process it runs)
    # ahead of the JSON makes the host fail to parse it, and Claude Code and Gemini CLI then
    # treat the hook as a non-blocking error: a deny became an allow, witnessed live.
    sink = sys.stderr if sys.stderr is not None else io.StringIO()
    held = (sys.stdout, sys.__stdout__)
    _flush(held)
    saved = _divert_fd1()
    try:
        with contextlib.redirect_stdout(sink):
            yield
    finally:
        if saved is not None:
            # A stream the handler held on to (sys.__stdout__, a reference cached at import)
            # buffers past redirect_stdout; flushed now it lands on stderr, not after the verdict.
            _flush((sink, *held))
            os.dup2(saved, 1)
            os.close(saved)


def _decide(raw):
    """(stdout_text, exit_code) for one decoded payload: agentseam.dispatch.handle(), inlined."""
    event = parse(raw)
    if event.event == UNKNOWN:
        # A vendor event this adapter has no mapping for. handle() is not called: it
        # reasons about the canonical vocabulary, and handing it something outside that
        # vocabulary invites a decision made on a false premise.
        return "", 0
    try:
        with _stdout_to_stderr():
            result = handle(event)
        decision = _coerce(result)
    except Exception:
        # A door that cannot decide refuses. Escaping here would exit 1 with a traceback,
        # which every host reads as a non-blocking error and allows past; instead the
        # failure is printed for the operator and the gate answers deny in 'vscode_copilot''s
        # own dialect. Only the failure's class is named to the host: its message may quote
        # the very payload content the policy was inspecting.
        _report(traceback.format_exc())
        decision = Decision.deny(
            "policy handler failed (%s); refusing rather than allowing what it could not judge"
            % sys.exc_info()[0].__name__
        )
    return _chock_copilot_respond(degrade(decision, event), event)


def main(stdin=None, stdout=None, exit=True):
    """Read one payload from stdin, dispatch, emit the 'vscode_copilot' response, exit."""
    stream = stdin if stdin is not None else sys.stdin
    out = stdout if stdout is not None else sys.stdout
    try:
        raw = json.loads(_read_payload(stream))
    except Exception:
        # Malformed input is not the agent's fault to pay for: allow, stay silent.
        if exit:
            sys.exit(0)
        return 0
    try:
        text, code = _decide(raw)
    except Exception:
        # Past the handler, which _decide() already answers for: a fault in this file on a
        # payload it did decode. With no Event to answer in dialect, the one refusal left is
        # the host's blocking exit code, and nothing on stdout to be misread as a verdict.
        _report(traceback.format_exc())
        text, code = "", 2
    if text:
        _emit(out, text)
    if exit:
        sys.exit(code)
    return code


if __name__ == "__main__":  # pragma: no cover
    main()

