#!/usr/bin/env bash
# Generated by Chock. Blocks git commit/push --no-verify or -n flag tokens.
# Best-effort guard; bypasses are possible via aliases, subshells, or non-standard clients.
set -eu

is_git_commit_or_push=0
subcommand=""

for arg in "$@"; do
    case "$arg" in
        git) ;;
        commit|push)
            is_git_commit_or_push=1
            subcommand="$arg"
            ;;
    esac
done

if [[ "$is_git_commit_or_push" -eq 0 ]]; then
    exit 0
fi

# `git -c core.hooksPath=<somewhere-empty> commit` disables every hook without ever typing
# --no-verify. Same intent, same outcome, and it was completely uncovered: a policy that
# blocks the flag while allowing the config override blocks the spelling, not the behaviour.
#
# Matched only as the VALUE FOLLOWING `-c`, never as free text. Scanning every argument
# blocked `git commit -m "core.hooksPath=... is a bypass"` -- a message that merely mentions
# the setting changes no configuration, and a guard that refuses people for describing the
# thing it guards against trains them to work around it.
# Compared lowercased: git config keys are case-insensitive, so -c CORE.HOOKSPATH=...
# bypasses hooks exactly as the canonical spelling does (verified against git directly).
# The bare valueless form `-c core.hooksPath` is deliberately NOT matched: git rejects it
# with rc=128 before any hook or commit runs, so there is nothing to block.
prev=""
for arg in "$@"; do
    if [[ "$prev" == "-c" && "${arg,,}" == core.hookspath=* ]]; then
        echo "BLOCKED: git $subcommand with -c core.hooksPath disables every hook, exactly as --no-verify does. Fix the failing hook instead of routing around it." >&2
        exit 1
    fi
    prev="$arg"
done

has_n=0
for arg in "$@"; do
    if [[ "$arg" == "--no-verify" ]]; then
        has_n=1
    elif [[ "$arg" == "-n" ]]; then
        has_n=1
    elif [[ "$arg" =~ ^-[^-] ]]; then
        # Combined short flags: block if the token contains 'n' (e.g. -nm).
        if [[ "$arg" == *n* ]]; then
            has_n=1
        fi
    fi
done

if [[ "$has_n" -eq 1 ]]; then
    echo "BLOCKED: git $subcommand --no-verify is not allowed. Fix the hook failure instead." >&2
    exit 1
fi

exit 0
