# Generated by agentseam 0.1.1 -- bundle("vscode_copilot"). Do not hand-edit, except the
# HANDLER block below (between "agentseam handler >>>" and "<<< agentseam handler"),
# which is exactly what this file leaves for you to fill in.
#
# Self-contained: stdlib only, no "import agentseam" anywhere in this file. Regenerate
# with `agentseam.bundler.bundle("vscode_copilot")` (same agentseam version -> identical bytes,
# except your own edits inside the handler block) rather than patching this by hand.
# https://github.com/open-coder-ai/agentseam

from __future__ import annotations

import json
_json = json
import sys

import os as _chock_os
import shlex as _chock_shlex
import subprocess as _chock_subprocess
from datetime import datetime as _chock_datetime, timezone as _chock_timezone
from pathlib import Path as _chock_Path

# ------------------------------------------------------------------------------
# contract (agentseam 0.1.1)

"""Canonical event vocabulary, normalized envelope, and decision type.

This is L0: the contract every adapter speaks. Nothing here knows any vendor.
Stdlib only — this module is embedded verbatim into rendered single-file adapters.
"""



# --- canonical lifecycle events -------------------------------------------------
# Vendor event names map ONTO these; adapters own the mapping. A vendor that lacks
# an event simply has no row for it in the capability matrix — that absence is the
# honest coverage floor, not something to paper over.
SESSION_START = "session_start"
SESSION_END = "session_end"
PROMPT_SUBMIT = "prompt_submit"
PRE_TOOL = "pre_tool"
POST_TOOL = "post_tool"
TOOL_FAILURE = "tool_failure"
PRE_COMPACT = "pre_compact"
STOP = "stop"
SUBAGENT_START = "subagent_start"
SUBAGENT_STOP = "subagent_stop"
INSTRUCTIONS_LOADED = "instructions_loaded"
FILE_CHANGED = "file_changed"

#: Not a lifecycle event: the honest answer when a vendor sends something this adapter has
#: no mapping for. Deliberately outside EVENTS, so a handler matching on the vocabulary can
#: never match it by accident.
#:
#: The alternative was what several adapters used to do -- fall back to the nearest
#: canonical event -- which reports an unknown event as `pre_tool` and invites a guardrail
#: to evaluate a pre-tool policy against something that is not one. New vendor events appear
#: without warning; being told is the only safe outcome.
UNKNOWN = "unknown"

EVENTS = (
    SESSION_START,
    SESSION_END,
    PROMPT_SUBMIT,
    PRE_TOOL,
    POST_TOOL,
    TOOL_FAILURE,
    PRE_COMPACT,
    STOP,
    SUBAGENT_START,
    SUBAGENT_STOP,
    INSTRUCTIONS_LOADED,
    FILE_CHANGED,
)

# --- normalized envelope --------------------------------------------------------


class Event:
    """One agent lifecycle event, normalized.

    `raw` is always kept: adapters normalize the fields consumers usually want, and
    a consumer that needs something vendor-specific can still reach it rather than
    being blocked by our vocabulary.
    """

    __slots__ = (
        "agent",
        "event",
        "tool",
        "command",
        "path",
        "content",
        "output",
        "prompt",
        "session_id",
        "tool_use_id",
        "cwd",
        "raw",
    )

    def __init__(
        self,
        agent,
        event,
        *,
        tool=None,
        command=None,
        path=None,
        content=None,
        output=None,
        prompt=None,
        session_id=None,
        tool_use_id=None,
        cwd=None,
        raw=None,
    ):
        self.agent = agent
        self.event = event
        self.tool = tool
        self.command = command  # shell command, when the tool carries one
        self.path = path  # target file, when the tool writes one
        self.content = content  # file text being written (pre_tool on write tools)
        self.output = output  # tool result (post_tool)
        self.prompt = prompt  # user prompt text (prompt_submit)
        self.session_id = session_id
        self.tool_use_id = tool_use_id
        self.cwd = cwd
        self.raw = raw if raw is not None else {}

    def __repr__(self):  # pragma: no cover - debugging aid
        return "Event(%s/%s tool=%r path=%r)" % (self.agent, self.event, self.tool, self.path)


# --- decisions ------------------------------------------------------------------

ALLOW = "allow"
DENY = "deny"
ASK = "ask"
REWRITE = "rewrite"
#: "I actively approve -- skip the user's own confirmation," never the default. ALLOW means
#: no objection; a bare ALLOW that spoke this loudly was the exact defect
#: allow_semantics.py exists to audit. VOUCH is that same loud word, used on purpose, on the
#: vendors it is established to mean this. See dispatch.degrade() and
#: allow_semantics.VOUCH_SPEAKS for which those are, and how everyone else degrades.
VOUCH = "vouch"


class Decision:
    """What a handler wants to happen. Adapters translate this to vendor dialect.

    `evidence` is an optional payload-free dict a consumer can carry through to its
    own log; agentseam never writes it anywhere itself.

    `context` is different: free text meant to reach the MODEL, on the few vendor
    surfaces that take side-channel context injection independent of the outcome
    (Claude Code's hookSpecificOutput.additionalContext at SessionStart and
    UserPromptSubmit today). An adapter with no such surface drops it silently --
    the same honest-degrade shape as an unsupported outcome, not a promise every
    vendor can keep. It is advisory content, never a substitute for `reason`, which
    still speaks to the vendor's own decision/refusal dialect.
    """

    __slots__ = ("outcome", "reason", "updated_input", "evidence", "context")

    def __init__(self, outcome, reason=None, updated_input=None, evidence=None, context=None):
        if outcome not in (ALLOW, DENY, ASK, REWRITE, VOUCH):
            raise ValueError("unknown outcome: %r" % (outcome,))
        self.outcome = outcome
        self.reason = reason
        self.updated_input = updated_input
        self.evidence = evidence or {}
        self.context = context

    # constructors read better at call sites than Decision("deny", ...)
    @classmethod
    def allow(cls, reason=None, evidence=None, context=None):
        return cls(ALLOW, reason, evidence=evidence, context=context)

    @classmethod
    def deny(cls, reason, evidence=None, context=None):
        return cls(DENY, reason, evidence=evidence, context=context)

    @classmethod
    def ask(cls, reason, evidence=None, context=None):
        return cls(ASK, reason, evidence=evidence, context=context)

    @classmethod
    def rewrite(cls, updated_input, reason=None, evidence=None, context=None):
        return cls(REWRITE, reason, updated_input=updated_input, evidence=evidence, context=context)

    @classmethod
    def vouch(cls, reason=None, evidence=None, context=None):
        return cls(VOUCH, reason, evidence=evidence, context=context)

    def __repr__(self):  # pragma: no cover - debugging aid
        return "Decision(%s, %r)" % (self.outcome, self.reason)


def degraded_from(decision):
    """What this decision was before the dispatcher reduced it, or None.

    An adapter explaining why an outcome changed shape has to read this, not the outcome
    it was handed. A rewrite reduced to `ask` and then blocked by an agent that cannot
    prompt would otherwise be reported as a confirmation request that failed -- and it was
    never a confirmation request.
    """
    return (decision.evidence or {}).get("degraded_from")


def tool_input_of(raw):
    """The tool's arguments as a dict, decoding the JSON-string form some vendors send.

    `tool_input` is whatever the agent chose to serialise, and it is not always an object.
    Witnessed live on VS Code Copilot (2026-08-29), same adapter and same `Edit` tool, in
    two runs routed to different models: once as an object with path/old_str/new_str, once
    as a 129-character JSON *string*. Both are the vendor's real wire format.

    That difference is not cosmetic. Against the object the parser reports the file and the
    content; against the string it reported neither, so a policy denying on secret content
    saw an empty write and allowed it. The adapters guarded the string case against a crash
    (a crash is an allow) but resolved it to `{}`, which is a quieter version of the same
    outcome: the guard is blind and says nothing about it.

    Decoding is not a guess about an unrecorded shape -- a string that parses to a JSON
    object IS that object, and the alternative is discarding data the vendor sent. Only a
    dict counts: a JSON list or scalar is not a set of tool arguments, and `{}` remains the
    honest answer for anything that does not parse.
    """
    if isinstance(raw, dict):
        return raw
    if isinstance(raw, str) and raw[:1] == "{":
        try:
            parsed = _json.loads(raw)
        except Exception:
            return {}
        if isinstance(parsed, dict):
            return parsed
    return {}


# ------------------------------------------------------------------------------
# windows helper (used by the vscode_copilot adapter)

"""PowerShell's one rule that breaks hook commands, shared by the vendors it affects.

Two adapters here need this and for the same reason, so the explanation lives once rather
than twice: a copy that drifts is how a vendor fact becomes two disagreeing vendor facts.
"""



def powershell_command(command):
    """`command` rewritten so PowerShell will actually run it.

    A command line that BEGINS with a quoted path is parsed by PowerShell as a string
    expression, not an invocation -- and a bare string followed by more arguments is a
    parse error, so nothing runs at all. `&` is PowerShell's call operator, and it makes a
    quoted path executable.

    Witnessed live (Codex CLI 0.150.1, Windows, 2026-08-28): the quoted form failed with
    "hook exited with code 1" on every event, and a `> file 2>&1` redirect appended to it
    produced NO file -- proof the line never reached execution, since PowerShell sets up
    redirection only for a command it could parse. Prefixing `&` ran the hook immediately.
    A bare `python3 "..."` also works, because it parses in command mode; the difference is
    the leading quote, not the interpreter.

    Both vendors route hooks through PowerShell on Windows. Codex wraps them itself;
    VS Code Copilot does it in hookExecutor.ts's getShellCommand, which spawns
    `powershell.exe -ExecutionPolicy Bypass -NoProfile -NoLogo -Command <hookCommand>`
    whenever ComSpec is cmd.exe -- i.e. by default. Each adapter passes the result through
    its own per-platform override field, so the POSIX `command` keeps the exact quoted
    interpreter path that installed the hook.
    """
    return command if command.lstrip().startswith("&") else "& " + command


# ------------------------------------------------------------------------------
# vscode_copilot adapter

"""VS Code Copilot (agent mode) and GitHub Copilot CLI adapter.

Two vendors, one hook surface, two spellings of every event name -- `HOOKS_BY_TARGET` in
microsoft/vscode's `hookTypes.ts` gives both maps side by side, PascalCase for
Target.VSCode and camelCase for Target.GitHubCopilot. See EVENT_MAP below.

Neither list contains `postToolUseFailure`, which this adapter mapped, claimed on and
installed for until 2026-08-28: the config key resolves to nothing, so an install for
tool_failure wired a hook that could never fire.

PreToolUse wire contract (hookCommandTypes.ts): IPreToolUseHookCommandInput {tool_name,
tool_input, tool_use_id} plus the envelope executeHook merges into every event; out,
hookSpecificOutput {permissionDecision: allow|deny|ask, permissionDecisionReason,
updatedInput, additionalContext}, honoured in languageModelToolsService.invokeTool.

The difference that matters for policy: a memory write is the `memory` tool
(create/str_replace/insert on /memories/...), not a file edit."""



AGENT = "vscode_copilot"

#: Every vendor event name, in both spellings; parsing accepts both. `errorOccurred` is absent:
#: it reports a session error, not a tool failure, so it would have a guardrail judge a tool
#: policy against a payload with no tool. PreCompact too: in the schema and docs, never fired.
EVENT_MAP = {
    # VS Code agent mode (Target.VSCode)
    "PreToolUse": PRE_TOOL,
    "PostToolUse": POST_TOOL,
    "UserPromptSubmit": PROMPT_SUBMIT,
    "SessionStart": SESSION_START,
    "SubagentStart": SUBAGENT_START,
    "SubagentStop": SUBAGENT_STOP,
    "Stop": STOP,
    # GitHub Copilot CLI / coding agent (Target.GitHubCopilot)
    "preToolUse": PRE_TOOL,
    "postToolUse": POST_TOOL,
    "userPromptSubmitted": PROMPT_SUBMIT,
    "sessionStart": SESSION_START,
    "sessionEnd": SESSION_END,
    "subagentStop": SUBAGENT_STOP,
    "agentStop": STOP,
}

MEMORY_TOOLS = ("memory", "copilot_memory")
MEMORY_WRITE_COMMANDS = ("create", "str_replace", "insert")
# A FILE_WRITE_TOOLS constant naming create_file/edit_file/apply_patch waited here for a
# live capture. It ran (2026-08-29): the write tool is `Edit`, sending path/old_str/new_str,
# keys the generic branch already read. What it does not always send is an OBJECT -- see
# tool_input_of.


#: Turn-scoped fields OpenAI Codex CLI sends and VS Code never does.
_CODEX_MARKERS = ("turn_id", "permission_mode")

#: Cursor's base hook schema, present on every one of its events.
_CURSOR_MARKERS = ("model", "cursor_version", "conversation_id", "generation_id", "workspace_roots")

#: Copilot CLI's camelCase names, which no other vendor uses -- the name alone identifies
#: these. Derived from EVENT_MAP: a hand-kept list drifted and left payloads unclaimed.
_CLAIMABLE = tuple(name for name in EVENT_MAP if name[:1].islower())

#: executeHook merges {timestamp, hook_event_name, session_id?, transcript_path?} into
#: EVERY VS Code payload. `timestamp` is the one field there that Claude Code -- whose
#: PascalCase names VS Code reuses exactly -- has never been observed to send, and
#: claude_code.claims() already declines on it. Tabnine sends it too, so SessionStart
#: stays ambiguous by design.
_VSCODE_ENVELOPE = "timestamp"


def claims(raw):
    """True for a payload from either product.

    Until 2026-08-28 this claimed camelCase only, so it never claimed a real VS Code payload:
    VS Code spells its events PascalCase, identically to Claude Code, so those went to
    claude_code alone and were answered in the wrong dialect at every event but one."""
    if not isinstance(raw, dict):
        return False
    name = raw.get("hook_event_name") or raw.get("hookEventName")
    # Positive evidence first: Cursor's `model` is in the exclusion list below and VS
    # Code's SessionStartHookInput carries `model` too, so running the exclusions first
    # rejected exactly the payload the envelope test identifies.
    if name in EVENT_MAP and _VSCODE_ENVELOPE in raw and "turn_id" not in raw:
        return True
    # Codex CLI and Cursor spell their events in this same camelCase and differ only in
    # the fields they carry, so without this guard two adapters claim the event, detection
    # goes ambiguous, and the dispatcher allows a write it was asked to gate. Each vendor
    # gets more than one marker on purpose: Cursor's `model` alone kept these apart until a
    # payload without it turned up, and then both adapters claimed it.
    if any(k in raw for k in _CODEX_MARKERS + _CURSOR_MARKERS):
        return False
    if name in _CLAIMABLE:
        return True
    # memory-tool payloads are unmistakable
    # The isinstance guard also keeps a non-dict tool_input from raising here.
    ti = raw.get("tool_input")
    return raw.get("tool_name") in MEMORY_TOOLS and isinstance(ti, dict) and "command" in ti


def parse(raw):
    ti = raw.get("tool_input")
    ti = tool_input_of(ti)
    tool = raw.get("tool_name") or raw.get("toolName")
    path = content = None
    if tool in MEMORY_TOOLS:
        if ti.get("command") in MEMORY_WRITE_COMMANDS:
            path = ti.get("path") or "/memories/"
            content = ti.get("file_text") or ti.get("new_str") or ti.get("insert_text")
        else:
            path = ti.get("path")
    else:
        path = ti.get("filePath") or ti.get("file_path") or ti.get("path")
        content = ti.get("content") or ti.get("newText") or ti.get("new_str")
    name = raw.get("hook_event_name") or raw.get("hookEventName") or "preToolUse"
    return Event(
        AGENT,
        # An unmapped event resolves to UNKNOWN, never to the nearest canonical one:
        # relabelling invites a guardrail to evaluate the wrong policy against it.
        EVENT_MAP.get(name, UNKNOWN),
        tool=tool,
        command=ti.get("command") if tool not in MEMORY_TOOLS else None,
        path=path,
        content=content,
        # The prompt text was once never read here, so a prompt policy saw None and was
        # silently dead; the envelope's peers (claude_code, gemini_cli) both read `prompt`.
        prompt=raw.get("prompt"),
        # IPostToolUseHookCommandInput names it `tool_response`. `tool_output` is Claude
        # Code's key, read here on an assumption, so event.output was always None on a real
        # PostToolUse payload and an output-inspecting policy was dead on this agent.
        output=raw.get("tool_output") or raw.get("tool_response"),
        session_id=raw.get("session_id"),
        tool_use_id=raw.get("tool_use_id"),
        cwd=raw.get("cwd"),
        raw=raw,
    )


def is_memory_write(event):
    """True when this event is a memory-tool content write (VS Code's memory surface)."""
    ti = event.raw.get("tool_input")
    ti = tool_input_of(ti)
    return event.tool in MEMORY_TOOLS and ti.get("command") in MEMORY_WRITE_COMMANDS


#: Block verdict at the TOP LEVEL: {decision: "block", reason}. UserPromptSubmitHookOutput
#: declares exactly those two and defaultIntentRequestHandler reads `typedOutput.decision`
#: off the root; executePostToolUseHook reads the same two off a PostToolUse response's root.
_TOP_LEVEL_BLOCK = (PROMPT_SUBMIT, POST_TOOL)

#: Block verdict NESTED in hookSpecificOutput. executeStopHook requires BOTH decision and
#: reason -- a block with no reason is discarded and the agent stops anyway.
_NESTED_BLOCK = (STOP, SUBAGENT_STOP)


def _echoed_name(event):
    """This event's own vendor spelling, out of the payload; VS Code's name if there is none."""
    raw = event.raw or {}
    return raw.get("hook_event_name") or raw.get("hookEventName") or REVERSE_EVENT_MAP.get(event.event, "PreToolUse")


def _refusal_reason(decision):
    """One reason string for the block dialects, which have no ask and no rewrite.

    Both degrade to a block with the degradation named, rather than being dropped: silence
    here is the dispatcher's allow, which is not what the caller asked for.
    """
    reason = decision.reason or "blocked by policy"
    if decision.outcome == ASK:
        return reason + " (confirmation requested; this event cannot prompt, so it blocks)"
    if decision.outcome == REWRITE:
        return reason + " (input rewrite requested; this event cannot modify input, so it blocks)"
    return reason


#: Decision words accepted: permissionDecision's allow/deny/ask (hookCommandTypes.ts) plus the "block" the two decision dialects read.
DECISION_VOCABULARY = frozenset({"allow", "deny", "ask", "block"})


def respond(decision, event):
    """Three dialects, one per event group -- not one gate shape everywhere.

    Until 2026-08-28 this emitted the PreToolUse gate JSON at every event; elsewhere that
    shape is not ignored but misread: UserPromptSubmit and PostToolUse take a top-level
    `decision`, Stop a nested one, and the start events swallow everything. hookEventName is
    echoed, not hardcoded (_toHookResult STRIPS hookSpecificOutput on a name mismatch).
    VOUCH has no word at either block dialect below -- only ever spoken at pre_tool."""
    import json as _json

    if event.event in _TOP_LEVEL_BLOCK:
        if decision.outcome in (ALLOW, VOUCH):
            return "", 0
        return _json.dumps({"decision": "block", "reason": _refusal_reason(decision)}), 0

    if event.event in _NESTED_BLOCK:
        if decision.outcome in (ALLOW, VOUCH):
            return "", 0
        out = {"hookEventName": _echoed_name(event), "decision": "block", "reason": _refusal_reason(decision)}
        return _json.dumps({"hookSpecificOutput": out}), 0

    if event.event != PRE_TOOL:
        # What is left is SessionStart and SubagentStart, which take additionalContext and
        # nothing else and run under `ignoreErrors: true`, plus anything that reached
        # UNKNOWN. None of them has a verdict shape to speak in, so none gets one.
        return "", 0

    if decision.outcome == ALLOW:
        # Silence, not permissionDecision:"allow": languageModelToolsService returns
        # `autoConfirmed: ConfirmationNotNeeded` on that value, skipping the user's
        # confirmation. A policy that did not match was doing that on every tool call.
        return "", 0

    out = {"hookEventName": _echoed_name(event)}
    if decision.outcome == VOUCH:
        # allow_semantics.VOUCH_SPEAKS names vscode_copilot, proven from source (unlike
        # claude_code's sibling inference): the exact value ALLOW withholds above.
        out["permissionDecision"] = "allow"
        if decision.reason:
            out["permissionDecisionReason"] = decision.reason
    elif decision.outcome == DENY:
        out["permissionDecision"] = "deny"
        out["permissionDecisionReason"] = decision.reason or "blocked"
    elif decision.outcome == ASK:
        out["permissionDecision"] = "ask"
        out["permissionDecisionReason"] = decision.reason or "confirmation required"
    elif decision.outcome == REWRITE:
        out["permissionDecision"] = "allow"
        out["updatedInput"] = decision.updated_input
        if decision.reason:
            out["permissionDecisionReason"] = decision.reason
    return _json.dumps({"hookSpecificOutput": out}), 0


#: Canonical -> vendor event, for installing. Module level so `install` can see which
#: events an adapter is able to wire; an inline map made that invisible, and an event the
#: matrix claimed but this could not name was dropped from the config without a word.
#:
#: PascalCase, i.e. VS Code's spelling, because CONFIG_PATH is VS Code's file.
#: `parseCopilotHooks` resolves each key with `resolveCopilotCliHookType(id) ?? toHookType
#: (id)`, so both spellings work -- but only one may be written: it does `result.set(...)`,
#: an overwrite, so two keys resolving to the same HookType silently drop one. SESSION_END
#: is therefore unwireable: a Copilot CLI name VS Code never fires.
REVERSE_EVENT_MAP = {
    PRE_TOOL: "PreToolUse",
    POST_TOOL: "PostToolUse",
    PROMPT_SUBMIT: "UserPromptSubmit",
    SESSION_START: "SessionStart",
    SUBAGENT_START: "SubagentStart",
    SUBAGENT_STOP: "SubagentStop",
    STOP: "Stop",
}


def hook_config(canonical_events, command, matcher=None):
    """The hooks file VS Code actually parses: an object keyed by event name.

    Until 2026-08-28 this emitted `{"version": 1, "hooks": [{"event": ...}]}` -- a LIST
    under `hooks`, an `event` key, no `type`. All three are wrong and the failure is
    silent: `parseCopilotHooks` iterates `Object.keys(hooksObj)`, which over a list yields
    "0", "1", "2", resolving to no hook type. Zero hooks are installed, with no error. A
    top-level `version` also flips the schema to the Copilot CLI branch, which rejects
    `command`.

    `windows` is the vendor's own per-platform override (normalizeHookCommand in
    hookSchema.ts), needed because hookExecutor.ts spawns `powershell.exe -Command
    <hookCommand>` whenever ComSpec is cmd.exe -- the Windows default -- and PowerShell will
    not run a line beginning with a quoted path. `command` keeps the POSIX form.

    `matcher` is accepted and ignored: extractHookCommandsFromItem reads Claude's
    `{matcher, hooks: [...]}` shape but discards the matcher, so there is no tool filter.
    """
    hooks = {}
    for ev in canonical_events:
        name = REVERSE_EVENT_MAP.get(ev)
        if name:
            entry = {"type": "command", "command": command, "windows": powershell_command(command)}
            hooks.setdefault(name, []).append(entry)
    return {"hooks": hooks}


CONFIG_PATH = ".github/hooks/agentseam.json"


# ------------------------------------------------------------------------------
# runtime (agentseam dispatch, specialized to vscode_copilot)

_VOUCH_SPEAKS = True
_REWRITE_EVENTS = frozenset(('pre_tool',))


def degrade(decision, event):
    """Reduce a decision to what 'vscode_copilot' can actually honor, honestly.

    This is agentseam.dispatch.degrade(), specialized to one fixed agent so this file needs
    no "import agentseam" -- claude_code and vscode_copilot are the only agents with real evidence that an explicit approval word means "skip confirmation"; see agentseam.allow_semantics.
    """
    if decision.outcome == REWRITE and event.event not in _REWRITE_EVENTS:
        evidence = dict(decision.evidence)
        evidence["degraded_from"] = REWRITE
        return Decision.ask(decision.reason or "input requires modification before it can run", evidence=evidence)
    if decision.outcome == VOUCH and not _VOUCH_SPEAKS:
        evidence = dict(decision.evidence)
        evidence["degraded_from"] = VOUCH
        return Decision.allow(decision.reason, evidence=evidence, context=decision.context)
    return decision


# >>> agentseam handler >>>
GUARD_VIOLATION = 1

_BASH_CANDIDATES = ('bash', 'C:\\Program Files\\Git\\usr\\bin\\bash.exe', 'C:\\Program Files\\Git\\bin\\bash.exe', 'C:\\Program Files (x86)\\Git\\usr\\bin\\bash.exe', '/bin/bash', '/usr/bin/bash')

GATE_LOG_ENV = 'CHOCK_GATE_LOG'

_LOG_MAX_BYTES = 1048576

_GUARD_TIMEOUT_SECONDS = 30

def guard_path_from_argv(argv: list[str]) -> _chock_Path | None:
    """The `--guard <path>` argument a vendored runtime was invoked with, or None.

    Read straight off argv rather than through argparse: every event a vendored runtime is
    ever invoked for goes through the same command line, chosen at install time
    (`hooks/*_install.py`), so there is nothing else on it to parse.
    """
    if '--guard' in argv:
        i = argv.index('--guard')
        if i + 1 < len(argv):
            return _chock_Path(argv[i + 1])
    return None

def find_bash(guard: _chock_Path) -> str | None:
    """First interpreter that can actually see `guard`, or None.

    The probe runs `test -f <guard>` rather than `--version`: the question is not whether
    a bash exists but whether *this* bash can resolve the path we are about to hand it.
    """
    for candidate in _BASH_CANDIDATES:
        try:
            proc = _chock_subprocess.run([candidate, '-c', f'test -f "{guard.as_posix()}"'], capture_output=True, timeout=10)
        except (OSError, _chock_subprocess.SubprocessError):
            continue
        if proc.returncode == 0:
            return candidate
    return None

def run_guard(guard: _chock_Path, command: str) -> bool | None:
    """True when the guard ran and reported a violation, False when it ran clean.

    None means the check did not happen -- unparseable command, no usable bash, a crash.
    That is distinct from False and must stay distinct: every "not checked" path still
    allows, so folding it into False changes no verdict, but it would let the outcome log
    record a passing guard for a check that never ran.

    Nothing here blocks on its own failure. Treating "could not run" as a violation would
    stop every Bash call the moment bash was missing -- turning a best-effort guard into a
    total outage. Failing open is stated loudly on stderr instead of silently.
    """
    try:
        args = _chock_shlex.split(command)
    except ValueError:
        print('chock: could not parse command (unbalanced quotes), not checked', file=sys.stderr)
        return None
    if not args:
        return None
    bash = find_bash(guard)
    if bash is None:
        print(f'chock: no usable bash found, {guard.name} not checked', file=sys.stderr)
        return None
    try:
        env = {**_chock_os.environ, 'CHOCK_RAW_COMMAND': command}
        proc = _chock_subprocess.run([bash, str(guard), *args], capture_output=True, text=True, encoding='utf-8', errors='replace', env=env, timeout=_GUARD_TIMEOUT_SECONDS)
    except (OSError, UnicodeError, _chock_subprocess.TimeoutExpired) as exc:
        print(f'chock: guard could not run, not checked: {exc}', file=sys.stderr)
        return None
    if proc.returncode == GUARD_VIOLATION:
        sys.stderr.write(proc.stdout or '')
        sys.stderr.write(proc.stderr or '')
        if not ((proc.stdout or '') + (proc.stderr or '')).strip():
            print(f'chock: blocked by {_chock_Path(guard).name} (guard gave no reason)', file=sys.stderr)
        return True
    if proc.returncode != 0:
        detail = (proc.stderr or proc.stdout or '').strip().splitlines()
        print(f'chock: guard exited {proc.returncode}, not checked' + (f': {detail[0][:120]}' if detail else ''), file=sys.stderr)
        return None
    return False

def log_outcome(guard: _chock_Path, tool: str, blocked: bool) -> None:
    """Append one outcome record. Best effort: never raises, never changes the verdict.

    Deliberately records NO command and no guard output. The command is the scanned content
    here, and commands routinely carry bearer tokens and passwords -- writing them to a
    plaintext file on every Bash call would create the exposure the secret policies exist to
    prevent. Which policy, which tool, and allow-or-block is the whole useful signal.
    """
    try:
        if _chock_os.environ.get(GATE_LOG_ENV) == '0':
            return
        guard = guard.resolve()
        if guard.parent.name != 'implementations':
            return
        artifact_root = None
        for parent in guard.parents:
            if (parent / '.chock').is_dir():
                artifact_root = parent / '.chock'
                break
        if artifact_root is None:
            return
        log_dir = artifact_root / 'log'
        log_dir.mkdir(parents=True, exist_ok=True)
        log_path = log_dir / 'gate-events.jsonl'
        if log_path.exists() and log_path.stat().st_size > _LOG_MAX_BYTES:
            log_path.replace(log_dir / 'gate-events.1.jsonl')
        import json
        record = {'ts': _chock_datetime.now(_chock_timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ'), 'policy_id': guard.parent.parent.name, 'surface': 'pre-tool-use', 'event': 'tool_use', 'kind': guard.stem, 'tool': tool, 'verdict': 'block' if blocked else 'allow'}
        with log_path.open('a', encoding='utf-8') as fh:
            fh.write(json.dumps(record, ensure_ascii=False) + '\n')
    except Exception:
        return

def evaluate(argv: list[str], command: str, tool: str='') -> str | None:
    """Run the guard named on `argv` (`--guard <path>`) against `command`.

    Returns the deny reason when the guard reports a violation, None on allow (including
    every "not checked" case -- the guard's own stderr already explains those). The one
    caller-facing entry point `gate.runtime_bundle`'s spliced handler uses: locate the
    guard, run it, log the outcome, word the verdict.
    """
    guard = guard_path_from_argv(argv)
    if guard is None or not guard.exists():
        return None
    blocked = run_guard(guard, command)
    if blocked is not None:
        log_outcome(guard, tool, blocked)
    return f'Blocked by chock policy: {guard.stem}' if blocked else None


def handle(event):
    if event.event == "pre_tool" and event.command:
        reason = evaluate(sys.argv[1:], event.command, event.tool or "")
        return Decision.deny(reason) if reason else None
    return None
# <<< agentseam handler <<<


def _coerce(result):
    if result is None:
        return Decision.allow()
    if isinstance(result, Decision):
        return result
    raise TypeError("handle() must return a Decision or None, got %r" % (type(result),))


def _read_payload(stream):
    # Decode bytes ourselves rather than trust the platform locale -- a BOM'd or non-UTF-8
    # stdin must not silently disable the gate. See agentseam.dispatch for the incident
    # this guards: a Windows console's cp1252 layer turning a UTF-8 BOM into three bytes
    # json cannot parse, with the hook allowing everything while claiming enforcement.
    buffer = getattr(stream, "buffer", None)
    if buffer is not None:
        return buffer.read().decode("utf-8-sig", errors="replace")
    return stream.read().lstrip("\ufeff")


def _emit(out, text):
    buffer = getattr(out, "buffer", None)
    if buffer is not None:
        buffer.write(text.encode("utf-8"))
        buffer.flush()
    else:
        out.write(text)
        out.flush()


def main(stdin=None, stdout=None, exit=True):
    """Read one payload from stdin, dispatch, emit the 'vscode_copilot' response, exit."""
    stream = stdin if stdin is not None else sys.stdin
    out = stdout if stdout is not None else sys.stdout
    try:
        raw = json.loads(_read_payload(stream))
    except Exception:
        # Malformed input is not the agent's fault to pay for: allow, stay silent.
        if exit:
            sys.exit(0)
        return 0
    event = parse(raw)
    if event.event == UNKNOWN:
        # A vendor event this adapter has no mapping for. handle() is not called: it
        # reasons about the canonical vocabulary, and handing it something outside that
        # vocabulary invites a decision made on a false premise.
        if exit:
            sys.exit(0)
        return 0
    decision = degrade(_coerce(handle(event)), event)
    text, code = respond(decision, event)
    if text:
        _emit(out, text)
    if exit:
        sys.exit(code)
    return code


if __name__ == "__main__":  # pragma: no cover
    main()

